echo auto-generated by afni_proc.py, Tue Jan  2 15:41:15 2018
auto-generated by afni_proc.py, Tue Jan  2 15:41:15 2018
echo (version 6.02, December 12, 2017)
(version 6.02, December 12, 2017)
echo execution started: `date`
date
execution started: Tue Jan  2 15:41:16 EST 2018
afni -ver
Precompiled binary linux_openmp_64: Dec 22 2017 (Version AFNI_17.3.09)
afni_history -check_date 23 Sep 2016
-- is current: afni_history as new as: 23 Sep 2016
               most recent entry is:   22 Dec 2017
if ( 0 ) then
if ( 0 > 0 ) then
set subj = tb9406
endif
set output_dir = tb9406.srtt_v3
if ( -d tb9406.srtt_v3 ) then
set runs = ( `count -digits 2 1 3` )
count -digits 2 1 3
mkdir tb9406.srtt_v3
mkdir tb9406.srtt_v3/stimuli
cp stim_times/stim_times_srtt/bl1_c1_unstr.txt stim_times/stim_times_srtt/bl2_c1_unstr.txt stim_times/stim_times_srtt/bl3_c1_unstr.txt stim_times/stim_times_srtt/bl1_c2_str.txt stim_times/stim_times_srtt/bl2_c2_str.txt stim_times/stim_times_srtt/bl3_c2_str.txt tb9406.srtt_v3/stimuli
3dcopy anat/Sag3DMPRAGEs002a1001.nii.gz tb9406.srtt_v3/Sag3DMPRAGEs002a1001
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
3dTcat -prefix tb9406.srtt_v3/pb00.tb9406.r01.tcat func_srtt/ep2dbold156s004a001.nii.gz[6..$]
++ 3dTcat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ elapsed time = 3.5 s
3dTcat -prefix tb9406.srtt_v3/pb00.tb9406.r02.tcat func_srtt/ep2dbold156s006a001.nii.gz[6..$]
++ 3dTcat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ elapsed time = 3.2 s
3dTcat -prefix tb9406.srtt_v3/pb00.tb9406.r03.tcat func_srtt/ep2dbold156s008a001.nii.gz[6..$]
++ 3dTcat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ elapsed time = 1.6 s
set tr_counts = ( 150 150 150 )
cd tb9406.srtt_v3
touch out.pre_ss_warn.txt
foreach run ( 01 02 03 )
3dToutcount -automask -fraction -polort 3 -legendre pb00.tb9406.r01.tcat+orig
++ 3dToutcount: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb9406.r01.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb9406.r01.tcat+orig.BRIK is 10.299996 degrees from plumb.
++ 28582 voxels passed mask/clip
1deval -a outcount.r01.1D -expr 1-step(a-0.1)
if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
1deval -a outcount.r01.1D{0} -expr step(a-0.4)
end
3dToutcount -automask -fraction -polort 3 -legendre pb00.tb9406.r02.tcat+orig
++ 3dToutcount: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb9406.r02.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb9406.r02.tcat+orig.BRIK is 10.299996 degrees from plumb.
++ 28622 voxels passed mask/clip
1deval -a outcount.r02.1D -expr 1-step(a-0.1)
if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
1deval -a outcount.r02.1D{0} -expr step(a-0.4)
end
3dToutcount -automask -fraction -polort 3 -legendre pb00.tb9406.r03.tcat+orig
++ 3dToutcount: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb9406.r03.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb9406.r03.tcat+orig.BRIK is 10.299996 degrees from plumb.
++ 28407 voxels passed mask/clip
1deval -a outcount.r03.1D -expr 1-step(a-0.1)
if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
1deval -a outcount.r03.1D{0} -expr step(a-0.4)
end
cat outcount.r01.1D outcount.r02.1D outcount.r03.1D
cat rm.out.cen.r01.1D rm.out.cen.r02.1D rm.out.cen.r03.1D
foreach run ( 01 02 03 )
3dDespike -NEW -nomask -prefix pb01.tb9406.r01.despike pb00.tb9406.r01.tcat+orig
++ 3dDespike: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb9406.r01.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb9406.r01.tcat+orig.BRIK is 10.299996 degrees from plumb.
++ Input dataset is in short format, but output will be in float format
++ ignoring first 0 time points, using last 150
++ using 150 time points => -corder 5
++ Loading dataset pb00.tb9406.r01.tcat+orig
++ processing all 131072 voxels in dataset
++ Procesing time series with NEW model fit algorithm
++ smash edit thresholds: 3.1 .. 5.0 MADs
 +   [ 3.457% .. 0.072% of normal distribution]
 +   [ 8.839% .. 3.125% of Laplace distribution]
++ start OpenMP thread #2
++ start OpenMP thread #1
++ start OpenMP thread #0
++ start OpenMP thread #3
++ start OpenMP thread #5
++ start OpenMP thread #4
........................................................
++ Elapsed despike time =  1s 784ms

++ FINAL: 19353600 data points, 704033 edits [3.638%], 39008 big edits [0.202%]
++ Output dataset ./pb01.tb9406.r01.despike+orig.BRIK
end
3dDespike -NEW -nomask -prefix pb01.tb9406.r02.despike pb00.tb9406.r02.tcat+orig
++ 3dDespike: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb9406.r02.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb9406.r02.tcat+orig.BRIK is 10.299996 degrees from plumb.
++ Input dataset is in short format, but output will be in float format
++ ignoring first 0 time points, using last 150
++ using 150 time points => -corder 5
++ Loading dataset pb00.tb9406.r02.tcat+orig
++ processing all 131072 voxels in dataset
++ Procesing time series with NEW model fit algorithm
++ smash edit thresholds: 3.1 .. 5.0 MADs
 +   [ 3.457% .. 0.072% of normal distribution]
 +   [ 8.839% .. 3.125% of Laplace distribution]
++ start OpenMP thread #0
++ start OpenMP thread #3
++ start OpenMP thread #5
++ start OpenMP thread #1
++ start OpenMP thread #2
++ start OpenMP thread #4
........................................................
++ Elapsed despike time =  1s 611ms

++ FINAL: 19353600 data points, 752336 edits [3.887%], 74845 big edits [0.387%]
++ Output dataset ./pb01.tb9406.r02.despike+orig.BRIK
end
3dDespike -NEW -nomask -prefix pb01.tb9406.r03.despike pb00.tb9406.r03.tcat+orig
++ 3dDespike: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb9406.r03.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb9406.r03.tcat+orig.BRIK is 10.299996 degrees from plumb.
++ Input dataset is in short format, but output will be in float format
++ ignoring first 0 time points, using last 150
++ using 150 time points => -corder 5
++ Loading dataset pb00.tb9406.r03.tcat+orig
++ processing all 131072 voxels in dataset
++ Procesing time series with NEW model fit algorithm
++ smash edit thresholds: 3.1 .. 5.0 MADs
 +   [ 3.457% .. 0.072% of normal distribution]
 +   [ 8.839% .. 3.125% of Laplace distribution]
++ start OpenMP thread #0
++ start OpenMP thread #1
++ start OpenMP thread #5
++ start OpenMP thread #3
++ start OpenMP thread #2
++ start OpenMP thread #4
........................................................
++ Elapsed despike time =  1s 595ms

++ FINAL: 19353600 data points, 744613 edits [3.847%], 62702 big edits [0.324%]
++ Output dataset ./pb01.tb9406.r03.despike+orig.BRIK
end
foreach run ( 01 02 03 )
3dTshift -tzero 0 -quintic -prefix pb02.tb9406.r01.tshift -tpattern alt+z2 pb01.tb9406.r01.despike+orig
++ 3dTshift: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb01.tb9406.r01.despike+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb01.tb9406.r01.despike+orig.BRIK is 10.299996 degrees from plumb.
end
3dTshift -tzero 0 -quintic -prefix pb02.tb9406.r02.tshift -tpattern alt+z2 pb01.tb9406.r02.despike+orig
++ 3dTshift: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb01.tb9406.r02.despike+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb01.tb9406.r02.despike+orig.BRIK is 10.299996 degrees from plumb.
end
3dTshift -tzero 0 -quintic -prefix pb02.tb9406.r03.tshift -tpattern alt+z2 pb01.tb9406.r03.despike+orig
++ 3dTshift: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb01.tb9406.r03.despike+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb01.tb9406.r03.despike+orig.BRIK is 10.299996 degrees from plumb.
end
3dbucket -prefix vr_base pb02.tb9406.r01.tshift+orig[0]
++ 3dbucket: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
align_epi_anat.py -anat2epi -anat Sag3DMPRAGEs002a1001+orig -save_skullstrip -suffix _al_junk -epi vr_base+orig -epi_base 0 -epi_strip 3dAutomask -giant_move -volreg off -tshift off
#++ align_epi_anat version: 1.57
#++ turning off volume registration
#Script is running (command trimmed):
  3dAttribute DELTA ./vr_base+orig
#Script is running (command trimmed):
  3dAttribute DELTA ./vr_base+orig
#Script is running (command trimmed):
  3dAttribute DELTA ./Sag3DMPRAGEs002a1001+orig
#++ Multi-cost is lpc
#++ Removing all the temporary files
#Script is running:
  \rm -f ./__tt_vr_base*
#Script is running:
  \rm -f ./__tt_Sag3DMPRAGEs002a1001*
#Script is running (command trimmed):
  3dcopy ./Sag3DMPRAGEs002a1001+orig ./__tt_Sag3DMPRAGEs002a1001+orig
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ Removing skull from anat data
#Script is running (command trimmed):
  3dSkullStrip -orig_vol -input ./__tt_Sag3DMPRAGEs002a1001+orig -prefix ./__tt_Sag3DMPRAGEs002a1001_ns
#Script is running (command trimmed):
  3dinfo ./__tt_Sag3DMPRAGEs002a1001_ns+orig | \grep 'Data Axes Tilt:'|\grep 'Oblique'
#++ Dataset /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/__tt_Sag3DMPRAGEs002a1001_ns+orig is not oblique
#Script is running (command trimmed):
  3dinfo ./vr_base+orig | \grep 'Data Axes Tilt:'|\grep 'Oblique'
#++ Dataset /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/vr_base+orig is ***oblique****
#Script is running (command trimmed):
  3dAttribute DELTA ./__tt_Sag3DMPRAGEs002a1001_ns+orig
#++ Spacing for anat to oblique epi alignment is 1.000000
#++ Matching obliquity of anat to epi
#Script is running (command trimmed):
  3dWarp -verb -card2oblique ./vr_base+orig -prefix ./__tt_Sag3DMPRAGEs002a1001_ns_ob -newgrid 1.000000 ./__tt_Sag3DMPRAGEs002a1001_ns+orig | \grep -A 4 '# mat44 Obliquity Transformation ::' > ./__tt_Sag3DMPRAGEs002a1001_ns_obla2e_mat.1D
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
#++ using 0th sub-brick because only one found
#Script is running (command trimmed):
  3dbucket -prefix ./__tt_vr_base_ts ./vr_base+orig'[0]'
++ 3dbucket: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ removing skull or area outside brain
#Script is running (command trimmed):
  3dAutomask -apply_prefix ./__tt_vr_base_ts_ns ./__tt_vr_base_ts+orig
++ 3dAutomask: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Emperor Zhark
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./__tt_vr_base_ts+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./__tt_vr_base_ts+orig.BRIK is 10.299996 degrees from plumb.
++ Loading dataset ./__tt_vr_base_ts+orig
++ Forming automask
 + Fixed clip level = 356.261078
 + Used gradual clip level = 337.030548 .. 377.979065
 + Number voxels above clip level = 30409
 + Clustering voxels ...
 + Largest cluster has 29193 voxels
 + Clustering voxels ...
 + Largest cluster has 28206 voxels
 + Filled   353 voxels in small holes; now have 28559 voxels
 + Filled     1 voxels in large holes; now have 28560 voxels
 + Clustering voxels ...
 + Largest cluster has 28559 voxels
 + Clustering non-brain voxels ...
 + Clustering voxels ...
 + Largest cluster has 102513 voxels
 + Mask now has 28559 voxels
++ 28559 voxels in the mask [out of 131072: 21.79%]
++ first  14 x-planes are zero [from R]
++ last   12 x-planes are zero [from L]
++ first   4 y-planes are zero [from P]
++ last    6 y-planes are zero [from A]
++ first   0 z-planes are zero [from I]
++ last    3 z-planes are zero [from S]
++ applying mask to original data
++ Writing masked data
++ Output dataset ./__tt_vr_base_ts_ns+orig.BRIK
++ CPU time = 0.000000 sec
#++ Computing weight mask
#Script is running (command trimmed):
  3dBrickStat -automask -percentile 90.000000 1 90.000000 ./__tt_vr_base_ts_ns+orig
#++ Applying threshold of 851.176514 on /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/__tt_vr_base_ts_ns+orig
#Script is running (command trimmed):
  3dcalc -datum float -prefix ./__tt_vr_base_ts_ns_wt -a ./__tt_vr_base_ts_ns+orig -expr 'min(1,(a/851.176514))'
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ././__tt_vr_base_ts_ns_wt+orig.BRIK
#++ Aligning anat data to epi data
#Script is running (command trimmed):
  3dAllineate -lpc -wtprefix ./__tt_Sag3DMPRAGEs002a1001_ns_ob_al_junk_wtal -weight ./__tt_vr_base_ts_ns_wt+orig -source ./__tt_Sag3DMPRAGEs002a1001_ns_ob+orig -prefix ./__tt_Sag3DMPRAGEs002a1001_ns_ob_temp_al_junk -base ./__tt_vr_base_ts_ns+orig -cmass -1Dmatrix_save ./Sag3DMPRAGEs002a1001_al_junk_e2a_only_mat.aff12.1D -master BASE -mast_dxyz 1.000000 -weight_frac 1.0 -maxrot 6 -maxshf 10 -VERB -warp aff -source_automask+4 -twobest 11 -twopass -VERB -maxrot 45 -maxshf 40 -fineblur 1 -source_automask+2 
++ 3dAllineate: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Registrator
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./__tt_vr_base_ts_ns_wt+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./__tt_vr_base_ts_ns_wt+orig.BRIK is 10.299996 degrees from plumb.
++ Oblique dataset:./__tt_vr_base_ts_ns+orig.BRIK is 10.299996 degrees from plumb.
++ Source dataset: ./__tt_Sag3DMPRAGEs002a1001_ns_ob+orig.HEAD
++ Base dataset:   ./__tt_vr_base_ts_ns+orig.HEAD
++ Loading datasets
++ 1672263 voxels in -source_automask+2
++ Zero-pad: zbot=4 ztop=1
++ 28559 voxels [18.8%] in weight mask
++ Output dataset ./__tt_Sag3DMPRAGEs002a1001_ns_ob_al_junk_wtal+orig.BRIK
++ Number of points for matching = 28559
++ NOTE: base and source coordinate systems have different handedness
 +       Orientations: base=Left handed (RPI); source=Right handed (RAI)
++ Local correlation: blok type = 'RHDD(13.3763)'
++ base center of mass = 32.340 29.629 18.252 (index)
 + source center of mass = 84.775 153.283 169.839 (index)
 + source-target CM = -0.788 1.488 5.271 (xyz)
 + center of mass shifts = -0.788 1.488 5.271
++ shift param auto-range: -70.3..68.7 -68.0..71.0 -41.0..51.5
 + Range param#4 [z-angle] = -6.000000 .. 6.000000
 + Range param#5 [x-angle] = -6.000000 .. 6.000000
 + Range param#6 [y-angle] = -6.000000 .. 6.000000
 + Range param#1 [x-shift] = -10.788071 .. 9.211929
 + Range param#2 [y-shift] = -8.511940 .. 11.488060
 + Range param#3 [z-shift] = -4.729385 .. 15.270615
 + Range param#4 [z-angle] = -45.000000 .. 45.000000
 + Range param#5 [x-angle] = -45.000000 .. 45.000000
 + Range param#6 [y-angle] = -45.000000 .. 45.000000
 + Range param#1 [x-shift] = -40.788071 .. 39.211929
 + Range param#2 [y-shift] = -38.511940 .. 41.488060
 + Range param#3 [z-shift] = -34.729385 .. 45.270615
 + 12 free parameters
++ Normalized convergence radius = 0.000463
++ changing output grid spacing to 1.0000 mm
++ OpenMP thread count = 6
++ ======= Allineation of 1 sub-bricks using Local Pearson Correlation Signed =======
 + source mask has 1672263 [out of 15629504] voxels
 + base mask has 39301 [out of 151552] voxels
++ ========== sub-brick #0 ========== [total CPU to here=0.0 s]
++ *** Coarse pass begins ***
 + * Enter alignment setup routine
 + - copying base image
 + - copying source image
 + - Smoothing base; radius=4.00
 + - Smoothing source; radius=4.00
 + !source mask fill: ubot=68 usiz=175
 + - copying weight image
 + - using 28559 points from base image [use_all=2]
 + * Exit alignment setup routine
 + - Search for coarse starting parameters
 + 24717 total points stored in 232 'RHDD(13.9615)' bloks
 + - number of free params = 6
 + - Testing (64+61)*64 params:#oo+++---+o-.-.+...+$.-- + - best 45 costs found:
    0 v=-0.091403:  -0.79   1.49   5.27   0.00   0.00   0.00  [grid]
    1 v=-0.039729: -14.12 -11.85  18.60 -15.00 -15.00 -15.00  [grid]
    2 v=-0.034182: -27.45 -25.18  31.94 -30.00 -15.00  30.00  [grid]
    3 v=-0.032389: -14.82 -14.23  19.94 -24.25 -37.55  -4.41  [rand]
    4 v=-0.032311: -11.11  30.30  20.28 -30.67  17.79  20.52  [rand]
    5 v=-0.031846: -14.12 -11.85  31.94 -15.00 -15.00 -15.00  [grid]
    6 v=-0.030943:  13.42  10.94  10.11 -15.99  13.53 -29.93  [rand]
    7 v=-0.030932: -16.77 -18.00  10.99 -20.53   3.14 -10.08  [rand]
    8 v=-0.030816: -14.12  14.82  18.60  15.00  15.00  15.00  [grid]
    9 v=-0.030622: -27.45 -11.85  31.94 -30.00 -15.00  30.00  [grid]
   10 v=-0.030512:  36.02 -31.60  25.47 -39.82 -23.12   9.72  [rand]
   11 v=-0.030317: -14.12 -25.18  31.94 -15.00 -30.00  15.00  [grid]
   12 v=-0.030078: -14.12  14.82  18.60  15.00  15.00  30.00  [grid]
   13 v=-0.029696: -14.12  28.15  18.60 -30.00  15.00  15.00  [grid]
   14 v=-0.029333: -14.12  28.15  18.60 -30.00  15.00  30.00  [grid]
   15 v=-0.028617: -14.12  14.82  18.60 -30.00  15.00  30.00  [grid]
   16 v=-0.028547: -25.75 -27.56  40.72  17.69 -14.58  34.92  [rand]
   17 v=-0.028429:  12.55 -25.18  31.94  15.00 -15.00 -30.00  [grid]
   18 v=-0.028243: -27.45  14.82  18.60 -30.00  30.00  30.00  [grid]
   19 v=-0.028183:  12.55  14.82  18.60 -15.00  15.00 -30.00  [grid]
   20 v=-0.028020: -23.14 -14.90  21.10 -41.11 -22.86  -3.97  [rand]
   21 v=-0.027839:  23.90  -3.12  21.66   8.97 -18.72 -30.56  [rand]
   22 v=-0.027316:  18.70  18.16   7.87 -30.54  19.59 -20.03  [rand]
   23 v=-0.027253:  25.88 -11.85  31.94  30.00  15.00 -30.00  [grid]
   24 v=-0.027242: -23.26 -27.66  35.30 -27.43 -11.56  19.13  [rand]
   25 v=-0.027048: -14.12 -25.18  18.60 -15.00 -15.00  15.00  [grid]
   26 v=-0.026941:  12.55  14.82  18.60 -30.00  15.00 -30.00  [grid]
   27 v=-0.026878: -14.12 -11.85  31.94 -15.00 -15.00  15.00  [grid]
   28 v=-0.026862:  -6.77   4.89  29.80  29.81   4.26  23.54  [rand]
   29 v=-0.026560: -14.12 -11.85  31.94 -30.00 -15.00  15.00  [grid]
   30 v=-0.026455:  12.55 -11.85  18.60  30.00 -15.00 -30.00  [grid]
   31 v=-0.026317: -14.12  14.82  31.94  15.00  15.00  30.00  [grid]
   32 v=-0.026308: -14.21 -21.20  36.61  -4.37 -20.12  15.12  [rand]
   33 v=-0.026188:  12.55  28.15  31.94 -30.00  30.00 -30.00  [grid]
   34 v=-0.026131:  16.07  20.07  19.72  19.57  37.09 -16.59  [rand]
   35 v=-0.026115: -27.45 -25.18  31.94  15.00 -15.00  30.00  [grid]
   36 v=-0.026086: -27.45 -25.18  31.94 -15.00 -15.00  30.00  [grid]
   37 v=-0.026057: -25.14 -28.20  18.30 -28.68 -38.91  32.36  [rand]
   38 v=-0.025948: -27.45  14.82  18.60 -15.00  15.00  30.00  [grid]
   39 v=-0.025623: -16.93  10.95  29.62 -20.99  15.73  16.09  [rand]
   40 v=-0.025603:  20.19 -26.89  37.52   3.65 -28.33 -14.78  [rand]
   41 v=-0.025579: -16.93  -7.98  29.62 -20.99 -15.73  16.09  [rand]
   42 v=-0.025576:  -6.77  -1.92  29.80  29.81   4.26  23.54  [rand]
   43 v=-0.025562:  24.18 -27.56  40.72 -17.69 -14.58 -34.92  [rand]
   44 v=-0.025411: -33.27 -13.20  17.08 -11.16  -9.40  34.39  [rand]
*[#8009=-0.127656] *[#8012=-0.151158] *[#8013=-0.191099] *[#8017=-0.192829] *[#8018=-0.199201] *[#8020=-0.207378] *[#8021=-0.207718] *[#8023=-0.208444] *[#8026=-0.20852] *[#8030=-0.208937] *[#8031=-0.209654]  + - costs of the above after a little optimization:
  * 0 v=-0.209654:   0.29  -1.65   4.99  -0.73  -0.16  -0.94  [grid]
    1 v=-0.057646: -12.75 -11.71  22.11 -15.35 -14.76 -15.75  [grid]
    2 v=-0.037911: -28.41 -23.02  31.69 -30.07 -15.14  29.89  [grid]
    3 v=-0.053372: -14.72 -14.78  21.74 -19.90 -31.20   0.65  [rand]
    4 v=-0.038320: -12.72  30.75  21.92 -29.30  15.92  19.41  [rand]
    5 v=-0.057358: -11.21 -11.28  27.18 -13.57 -18.06 -13.11  [grid]
    6 v=-0.038958:  14.76  11.87  15.74 -19.17  14.23 -31.43  [rand]
    7 v=-0.044931: -14.76 -15.66  12.03 -19.31   4.21 -11.85  [rand]
    8 v=-0.045816: -13.98   9.55  20.25  16.05  14.86  21.51  [grid]
    9 v=-0.043886: -28.63 -21.65  31.79 -27.58 -16.78  33.43  [grid]
   10 v=-0.036193:  36.09 -27.15  25.02 -40.19 -23.94   9.67  [rand]
   11 v=-0.058666: -13.64 -21.29  29.14  -4.27 -32.04  15.94  [grid]
   12 v=-0.047046: -14.10  10.65  20.01  14.78  15.33  29.80  [grid]
   13 v=-0.035560: -12.66  31.18  18.83 -29.72  16.14  14.34  [grid]
   14 v=-0.032918: -14.01  28.67  22.31 -29.96  14.97  30.26  [grid]
   15 v=-0.034630: -18.41  14.76  18.40 -30.01  15.17  29.87  [grid]
   16 v=-0.032175: -25.90 -23.23  40.38  17.28 -14.63  34.87  [rand]
   17 v=-0.034456:  13.44 -24.70  35.84  12.09 -18.10 -30.42  [grid]
   18 v=-0.029027: -27.46  15.29  19.13 -29.84  29.95  30.31  [grid]
   19 v=-0.040190:  13.15  13.68  17.24 -17.14  19.75 -29.17  [grid]
   20 v=-0.035783: -21.92  -9.63  21.08 -39.95 -22.30  -2.82  [rand]
   21 v=-0.050426:  22.52  -4.70  19.34   5.69 -11.46 -35.53  [rand]
   22 v=-0.031539:  18.70  18.83   8.26 -26.23  19.16 -20.48  [rand]
   23 v=-0.029066:  26.09 -14.31  29.00  31.20  14.41 -30.25  [grid]
   24 v=-0.039374: -24.22 -16.43  38.06 -25.81 -11.96  24.30  [rand]
   25 v=-0.038874: -14.29 -29.35  18.71 -16.08 -20.24  15.08  [grid]
   26 v=-0.037312:  13.96  16.16  16.15 -20.54  16.25 -33.59  [grid]
   27 v=-0.036231: -14.75 -12.07  27.44 -14.34 -16.34  14.64  [grid]
   28 v=-0.039883: -11.60   3.28  27.22  27.58   3.39  26.12  [rand]
   29 v=-0.041980: -16.56 -10.35  33.37 -27.51  -9.90  17.21  [grid]
   30 v=-0.045636:  16.34  -8.76  16.43  33.62 -18.55 -29.49  [grid]
   31 v=-0.033351: -15.47  13.04  28.95  14.06  12.96  35.92  [grid]
   32 v=-0.044612: -13.59 -24.56  33.82  -4.68 -26.85  16.17  [rand]
   33 v=-0.032487:  12.25  23.32  31.55 -30.61  30.81 -30.70  [grid]
   34 v=-0.033895:  16.52  16.96  19.64  19.52  37.69 -16.64  [rand]
   35 v=-0.035881: -27.73 -20.33  32.23  15.17 -15.16  30.71  [grid]
   36 v=-0.044208: -27.51 -22.44  34.69 -15.29 -17.98  36.13  [grid]
   37 v=-0.045113: -20.85 -28.14  20.63 -29.14 -39.54  31.33  [rand]
   38 v=-0.040937: -20.65  13.34  18.86 -14.05  16.66  31.26  [grid]
   39 v=-0.045952: -15.86   6.07  28.98 -19.22  21.00  15.40  [rand]
   40 v=-0.026571:  19.57 -27.26  36.96   2.46 -28.74 -16.86  [rand]
   41 v=-0.045210: -22.56  -4.26  24.61 -15.10 -16.21  14.06  [rand]
   42 v=-0.038202:  -8.07   3.24  28.32  28.35   2.49  20.42  [rand]
   43 v=-0.028756:  24.63 -23.77  40.44 -18.33 -14.61 -35.06  [rand]
   44 v=-0.039416: -32.89 -12.48  18.35  -9.23 -10.81  39.16  [rand]
 + - save # 0 for twobest
 + - save #11 for twobest
 + - save # 1 for twobest
 + - save # 5 for twobest
 + - save # 3 for twobest
 + - save #21 for twobest
 + - save #12 for twobest
 + - save #39 for twobest
 + - save # 8 for twobest
 + - save #30 for twobest
 + - save #41 for twobest
 + - save #37 for twobest
 + - save # 7 for twobest
 + - save #32 for twobest
 + - save #36 for twobest
 + - save # 9 for twobest
 + - save #29 for twobest
 + - save #38 for twobest
 + - save #19 for twobest
 + - save #28 for twobest
 + - save #44 for twobest
 + - save #24 for twobest
 + - Coarse startup search net CPU time = 0.0 s
++ Start refinement #1 on 12 coarse parameter sets
 + * Enter alignment setup routine
 + - Smoothing base; radius=3.11
 + - Smoothing source; radius=3.11
 + !source mask fill: ubot=68 usiz=175
 + - retaining old weight image
 + - using 28559 points from base image [use_all=2]
 + * Exit alignment setup routine
 + 25058 total points stored in 254 'RHDD(13.7332)' bloks
*[#9511=-0.237411] *[#9532=-0.239574] *[#9534=-0.239791] *[#9538=-0.239806] *[#9539=-0.239968] *[#9545=-0.240521] *[#9546=-0.240834] *[#9549=-0.241342] *[#9550=-0.241799] *[#9555=-0.241898] *[#9559=-0.242544] *[#9560=-0.243272] *[#9563=-0.243502] *[#9564=-0.24352] *[#9566=-0.244156] *[#9567=-0.244496] *[#9568=-0.244778] *[#9569=-0.245288] *[#9570=-0.245515] *[#9571=-0.245782] *[#9572=-0.246202] *[#9574=-0.246366] *[#9575=-0.246739] *[#9576=-0.246777] *[#9580=-0.246845] *[#9583=-0.247276] *[#9588=-0.247539] *[#9589=-0.247731] *[#9591=-0.247927] *[#9592=-0.248283] *[#9593=-0.248381] *[#9595=-0.24851] *[#9596=-0.249071] *[#9597=-0.249414] *[#9598=-0.249676] *[#9601=-0.249746] *[#9604=-0.250285] 
 + - param set #1 has cost=-0.250285
 + -- Parameters = 0.2750 -0.2330 5.1272 -0.8284 -0.4297 -0.7681 0.9923 1.0251 0.9981 -0.0065 -0.0045 0.0002
 + - param set #2 has cost=-0.050858
 + -- Parameters = -13.7218 -21.4423 29.2052 -4.2548 -31.9926 15.8526 1.0004 1.0000 1.0004 0.0001 0.0096 0.0003
 + - param set #3 has cost=-0.062301
 + -- Parameters = -9.8948 -11.4304 21.5358 -11.4497 -14.0274 -7.2461 1.0186 1.0016 0.9966 -0.0058 0.0038 -0.0007
 + - param set #4 has cost=-0.054987
 + -- Parameters = -10.2570 -11.9980 26.8265 -11.9939 -18.7848 -6.3632 1.0168 1.0033 1.0056 -0.0057 0.0028 -0.0020
 + - param set #5 has cost=-0.054142
 + -- Parameters = -12.6485 -15.5366 21.3982 -17.9208 -30.7243 0.5436 1.0264 0.9957 1.0098 0.0021 0.0003 0.0000
 + - param set #6 has cost=-0.049690
 + -- Parameters = 20.9398 -5.1753 13.6628 4.8719 -9.3666 -34.2947 1.0059 1.0058 1.0013 0.0048 0.0040 0.0019
 + - param set #7 has cost=-0.039283
 + -- Parameters = -15.0398 10.4299 19.8569 15.6140 18.8407 29.1478 0.9973 0.9992 1.0010 0.0005 0.0002 -0.0015
 + - param set #8 has cost=-0.033751
 + -- Parameters = -15.8206 5.6959 28.9436 -18.9711 22.9428 15.7646 1.0054 1.0009 1.0016 0.0010 0.0159 0.0016
 + - param set #9 has cost=-0.036441
 + -- Parameters = -14.0143 9.7806 20.7150 16.1475 14.4676 21.4240 0.9995 1.0018 0.9988 0.0100 -0.0015 0.0005
 + - param set #10 has cost=-0.046949
 + -- Parameters = 15.7924 -9.7477 16.6506 33.7619 -19.3907 -29.5799 1.0269 0.9994 1.0015 0.0039 0.0037 0.0041
 + - param set #11 has cost=-0.039391
 + -- Parameters = -22.4957 -3.8161 24.5332 -15.0832 -16.3299 13.5191 0.9995 0.9996 1.0011 0.0117 0.0013 -0.0019
 + - param set #12 has cost=-0.242902
 + -- Parameters = 0.6064 -1.1707 4.9738 -0.5267 -0.2585 -0.9646 0.9997 1.0027 0.9979 -0.0011 -0.0009 -0.0007
 + - sorting parameter sets by cost
 + -- scanning for distances from #1
 + --- dist(#2,#1) = 0.061 
 + --- dist(#3,#1) = 0.205 
 + --- dist(#4,#1) = 0.271 
 + --- dist(#5,#1) = 0.337 
 + --- dist(#6,#1) = 0.351 
 + --- dist(#7,#1) = 0.373 
 + --- dist(#8,#1) = 0.384 
 + --- dist(#9,#1) = 0.285 
 + --- dist(#10,#1) = 0.332 
 + --- dist(#11,#1) = 0.247 
 + --- dist(#12,#1) = 0.298 
++ Start refinement #2 on 12 coarse parameter sets
 + * Enter alignment setup routine
 + - Smoothing base; radius=2.42
 + - Smoothing source; radius=2.42
 + !source mask fill: ubot=68 usiz=175
 + - retaining old weight image
 + - using 28559 points from base image [use_all=2]
 + * Exit alignment setup routine
 + 25179 total points stored in 261 'RHDD(13.5933)' bloks
*[#10408=-0.264518] *[#10415=-0.264883] *[#10418=-0.265817] *[#10427=-0.267285] *[#10431=-0.268438] *[#10432=-0.268887] *[#10442=-0.269009] *[#10443=-0.269039] *[#10444=-0.269436] *[#10446=-0.269513] *[#10447=-0.269649] *[#10449=-0.269792] *[#10452=-0.269813] *[#10453=-0.269999] *[#10455=-0.270114] *[#10456=-0.270194] *[#10457=-0.270255] *[#10460=-0.270262] *[#10464=-0.270386] *[#10469=-0.270524] *[#10471=-0.270592] *[#10472=-0.270707] *[#10473=-0.270758] *[#10476=-0.270919] *[#10477=-0.271014] *[#10478=-0.271088] *[#10479=-0.27112] *[#10482=-0.271418] *[#10489=-0.271533] *[#10492=-0.271573] *[#10496=-0.271673] *[#10499=-0.271726] *[#10504=-0.271843] *[#10506=-0.27189] 
 + - param set #1 has cost=-0.271890
 + -- Parameters = 0.4607 -0.4837 4.9231 -0.6803 -0.6745 -0.6500 1.0007 1.0180 0.9961 0.0043 -0.0005 -0.0072
 + - param set #2 has cost=-0.266782
 + -- Parameters = 0.4784 -1.1907 4.8224 -0.6647 -0.1540 -0.9952 0.9993 1.0031 0.9977 -0.0009 0.0062 -0.0010
 + - param set #3 has cost=-0.059622
 + -- Parameters = -9.2333 -10.8816 21.8084 -10.1034 -15.0025 -3.3153 1.0232 1.0000 0.9923 -0.0017 0.0019 0.0036
 + - param set #4 has cost=-0.053695
 + -- Parameters = -9.4055 -15.1890 25.0525 -10.9548 -17.7081 -5.6933 1.0430 0.9569 1.0058 -0.0178 0.0086 -0.0055
 + - param set #5 has cost=-0.050232
 + -- Parameters = -11.5015 -16.3538 21.4106 -17.7184 -30.7943 0.0603 1.0241 1.0171 1.0223 -0.0043 0.0000 -0.0042
 + - param set #6 has cost=-0.044624
 + -- Parameters = -13.2031 -21.4428 29.3672 -4.2854 -31.9437 15.2448 1.0011 1.0003 0.9987 -0.0006 0.0119 0.0086
 + - param set #7 has cost=-0.041243
 + -- Parameters = 21.0005 -5.2046 13.5695 4.9354 -9.4096 -34.2010 1.0070 1.0068 1.0049 0.0105 0.0027 0.0036
 + - param set #8 has cost=-0.039034
 + -- Parameters = 16.1401 -9.6178 16.5716 33.7645 -19.6936 -29.6841 1.0258 0.9984 0.9992 0.0030 0.0031 0.0116
 + - param set #9 has cost=-0.031440
 + -- Parameters = -22.4000 -3.8538 24.4849 -15.0345 -16.5712 13.4070 0.9960 0.9961 0.9986 0.0187 0.0005 -0.0036
 + - param set #10 has cost=-0.029210
 + -- Parameters = -15.0698 10.4140 19.8100 15.6272 18.9471 29.2821 0.9970 0.9993 1.0014 0.0003 -0.0006 -0.0013
 + - param set #11 has cost=-0.026622
 + -- Parameters = -13.9268 9.7934 20.6456 16.7782 17.6729 20.9106 0.9990 0.9991 0.9997 0.0097 -0.0008 0.0016
 + - param set #12 has cost=-0.026408
 + -- Parameters = -15.6207 5.6766 28.9497 -18.9233 22.8610 15.7966 1.0048 1.0004 1.0005 0.0072 0.0150 0.0006
 + - sorting parameter sets by cost
 + -- scanning for distances from #1
 + --- dist(#2,#1) = 0.0405 
 + --- dist(#3,#1) = 0.211 
 + --- dist(#4,#1) = 0.252 
 + --- dist(#5,#1) = 0.335 
 + --- dist(#6,#1) = 0.347 
 + --- dist(#7,#1) = 0.373 
 + --- dist(#8,#1) = 0.383 
 + --- dist(#9,#1) = 0.286 
 + --- dist(#10,#1) = 0.333 
 + --- dist(#11,#1) = 0.24 
 + --- dist(#12,#1) = 0.3 
++ Start refinement #3 on 12 coarse parameter sets
 + * Enter alignment setup routine
 + - Smoothing base; radius=1.88
 + - Smoothing source; radius=1.88
 + !source mask fill: ubot=68 usiz=175
 + - retaining old weight image
 + - using 28559 points from base image [use_all=2]
 + * Exit alignment setup routine
 + 25319 total points stored in 268 'RHDD(13.5079)' bloks
 + - param set #1 has cost=-0.263564
 + -- Parameters = 0.5469 -0.6157 4.7622 -0.5885 -0.9544 -0.5690 0.9971 1.0119 0.9937 0.0020 -0.0018 -0.0166
 + - param set #2 has cost=-0.261488
 + -- Parameters = 0.5738 -0.7475 4.7057 -0.6376 -0.4401 -0.7666 1.0005 1.0107 0.9971 -0.0000 0.0007 -0.0075
 + - param set #3 has cost=-0.053319
 + -- Parameters = -8.7674 -10.9995 21.5818 -9.5561 -15.1054 -3.3776 1.0156 1.0113 0.9763 -0.0115 0.0059 0.0036
 + - param set #4 has cost=-0.046354
 + -- Parameters = -8.7976 -15.1211 25.2395 -10.1940 -17.6759 -6.0383 1.0472 0.9671 0.9918 -0.0230 0.0063 -0.0027
 + - param set #5 has cost=-0.042738
 + -- Parameters = -11.0254 -16.6023 20.9038 -17.8285 -30.4125 -0.8528 1.0283 1.0249 1.0246 -0.0029 -0.0039 -0.0029
 + - param set #6 has cost=-0.041301
 + -- Parameters = -13.2988 -21.5858 29.9481 -4.6752 -31.5716 14.6207 0.9986 1.0022 0.9755 -0.0010 0.0321 0.0103
 + - param set #7 has cost=-0.035847
 + -- Parameters = 20.7911 -4.8464 13.8270 4.5099 -9.4113 -34.1304 1.0066 1.0102 1.0111 0.0179 0.0086 0.0040
 + - param set #8 has cost=-0.032020
 + -- Parameters = 16.3250 -9.5244 16.5756 33.8252 -19.6885 -29.8248 1.0277 1.0006 0.9986 0.0027 0.0038 0.0112
 + - param set #9 has cost=-0.026609
 + -- Parameters = -22.4063 -3.8423 24.5903 -15.0868 -16.4946 13.4569 0.9956 0.9957 0.9985 0.0193 0.0011 -0.0036
 + - param set #10 has cost=-0.026549
 + -- Parameters = -15.1162 10.0801 19.8148 14.2028 18.3703 29.5144 0.9922 0.9985 1.0023 0.0010 -0.0004 -0.0011
 + - param set #11 has cost=-0.023844
 + -- Parameters = -13.1610 10.3911 20.6574 15.5001 18.1704 21.0391 0.9965 0.9942 0.9946 0.0087 -0.0024 0.0007
 + - param set #12 has cost=-0.022097
 + -- Parameters = -15.5866 5.6561 28.6524 -19.0689 22.9210 16.2101 1.0056 1.0002 1.0017 0.0111 0.0144 0.0002
 + - sorting parameter sets by cost
 + -- scanning for distances from #1
 + --- dist(#2,#1) = 0.0407 
 + --- dist(#3,#1) = 0.21 
 + --- dist(#4,#1) = 0.256 
 + --- dist(#5,#1) = 0.327 
 + --- dist(#6,#1) = 0.34 
 + --- dist(#7,#1) = 0.373 
 + --- dist(#8,#1) = 0.382 
 + --- dist(#9,#1) = 0.287 
 + --- dist(#10,#1) = 0.334 
 + --- dist(#11,#1) = 0.24 
 + --- dist(#12,#1) = 0.299 
 + - Total coarse refinement net CPU time = 0.0 s; 2940 funcs
++ *** Fine pass begins ***
 + * Enter alignment setup routine
 + - Smoothing base; radius=1.00
 + - Smoothing source; radius=1.00
 + !source mask fill: ubot=68 usiz=175
 + - retaining old weight image
 + * Exit alignment setup routine
++ Picking best parameter set out of 13 cases
 + 25535 total points stored in 274 'RHDD(13.4252)' bloks
 + - cost(#1)=-0.251482 *
 + -- Parameters = 0.5469 -0.6157 4.7622 -0.5885 -0.9544 -0.5690 0.9971 1.0119 0.9937 0.0020 -0.0018 -0.0166
 + - cost(#2)=-0.249600  
 + -- Parameters = 0.5738 -0.7475 4.7057 -0.6376 -0.4401 -0.7666 1.0005 1.0107 0.9971 -0.0000 0.0007 -0.0075
 + - cost(#3)=-0.045474  
 + -- Parameters = -8.7674 -10.9995 21.5818 -9.5561 -15.1054 -3.3776 1.0156 1.0113 0.9763 -0.0115 0.0059 0.0036
 + - cost(#4)=-0.039556  
 + -- Parameters = -8.7976 -15.1211 25.2395 -10.1940 -17.6759 -6.0383 1.0472 0.9671 0.9918 -0.0230 0.0063 -0.0027
 + - cost(#5)=-0.036418  
 + -- Parameters = -11.0254 -16.6023 20.9038 -17.8285 -30.4125 -0.8528 1.0283 1.0249 1.0246 -0.0029 -0.0039 -0.0029
 + - cost(#6)=-0.036046  
 + -- Parameters = -13.2988 -21.5858 29.9481 -4.6752 -31.5716 14.6207 0.9986 1.0022 0.9755 -0.0010 0.0321 0.0103
 + - cost(#7)=-0.030198  
 + -- Parameters = 20.7911 -4.8464 13.8270 4.5099 -9.4113 -34.1304 1.0066 1.0102 1.0111 0.0179 0.0086 0.0040
 + - cost(#8)=-0.027228  
 + -- Parameters = 16.3250 -9.5244 16.5756 33.8252 -19.6885 -29.8248 1.0277 1.0006 0.9986 0.0027 0.0038 0.0112
 + - cost(#9)=-0.020105  
 + -- Parameters = -22.4063 -3.8423 24.5903 -15.0868 -16.4946 13.4569 0.9956 0.9957 0.9985 0.0193 0.0011 -0.0036
 + - cost(#10)=-0.021636  
 + -- Parameters = -15.1162 10.0801 19.8148 14.2028 18.3703 29.5144 0.9922 0.9985 1.0023 0.0010 -0.0004 -0.0011
 + - cost(#11)=-0.020455  
 + -- Parameters = -13.1610 10.3911 20.6574 15.5001 18.1704 21.0391 0.9965 0.9942 0.9946 0.0087 -0.0024 0.0007
 + - cost(#12)=-0.017257  
 + -- Parameters = -15.5866 5.6561 28.6524 -19.0689 22.9210 16.2101 1.0056 1.0002 1.0017 0.0111 0.0144 0.0002
 + - cost(#13)=-0.109993  
 + -- Parameters = -0.7881 1.4881 5.2706 0.0000 0.0000 0.0000 1.0000 1.0000 1.0000 0.0000 0.0000 0.0000
 + -num_rtb 99 ==> refine all 13 cases
 + - cost(#1)=-0.253397 *
 + -- Parameters = 0.5822 -0.6743 4.5864 -0.4900 -0.9439 -0.6381 1.0026 1.0090 1.0026 0.0036 -0.0034 -0.0179
 + - cost(#2)=-0.251729  
 + -- Parameters = 0.5071 -0.6683 4.7403 -0.6204 -0.7447 -0.7488 1.0029 1.0112 1.0058 0.0021 -0.0008 -0.0113
 + - cost(#3)=-0.046018  
 + -- Parameters = -8.8191 -10.8455 21.4104 -9.5295 -15.0812 -3.4253 1.0186 1.0123 0.9768 -0.0084 0.0073 -0.0008
 + - cost(#4)=-0.040264  
 + -- Parameters = -8.7230 -15.0055 25.2645 -10.0345 -17.7645 -5.9926 1.0517 0.9642 0.9904 -0.0235 0.0017 -0.0017
 + - cost(#5)=-0.037192  
 + -- Parameters = -10.9625 -16.4744 20.6347 -17.7452 -30.2729 -0.5786 1.0302 1.0251 1.0213 -0.0028 -0.0015 -0.0033
 + - cost(#6)=-0.036678  
 + -- Parameters = -13.2804 -21.5967 29.8737 -4.4550 -31.5796 14.5603 0.9972 1.0025 0.9767 -0.0015 0.0337 0.0144
 + - cost(#7)=-0.031092  
 + -- Parameters = 20.7727 -5.0550 14.2367 4.2696 -9.3984 -34.2765 1.0113 1.0125 1.0137 0.0216 0.0080 0.0074
 + - cost(#8)=-0.027615  
 + -- Parameters = 16.3711 -9.6020 16.5501 33.8242 -19.4726 -29.8361 1.0290 1.0022 0.9975 0.0064 0.0052 0.0111
 + - cost(#9)=-0.020580  
 + -- Parameters = -22.4171 -3.8989 24.5445 -14.8484 -16.3090 13.7171 0.9966 1.0084 0.9984 0.0175 0.0015 -0.0040
 + - cost(#10)=-0.021907  
 + -- Parameters = -15.1372 10.0695 19.9868 14.2644 18.3275 29.4686 0.9920 0.9990 1.0087 0.0007 -0.0001 -0.0014
 + - cost(#11)=-0.024437  
 + -- Parameters = -14.1155 10.0757 20.0520 13.0981 18.4423 20.7286 0.9957 0.9797 0.9981 0.0190 -0.0124 0.0128
 + - cost(#12)=-0.020687  
 + -- Parameters = -15.7703 2.9685 30.9616 -19.1779 21.5741 15.7636 1.0063 1.0015 0.9994 0.0098 0.0164 0.0008
 + - cost(#13)=-0.250508  
 + -- Parameters = 0.5264 -0.7572 4.5717 -0.6312 -0.4593 -0.8347 0.9986 1.0070 0.9963 0.0021 0.0006 -0.0094
 + - case #1 is now the best
 + - Initial  cost = -0.253397
 + - Initial fine Parameters = 0.5822 -0.6743 4.5864 -0.4900 -0.9439 -0.6381 1.0026 1.0090 1.0026 0.0036 -0.0034 -0.0179
 + - Finalish cost = -0.254056 ; 383 funcs
 + - Final    cost = -0.254058 ; 93 funcs
 + Final fine fit Parameters:
       x-shift= 0.6046   y-shift=-0.6577   z-shift= 4.4844
       z-angle=-0.4943   x-angle=-1.2690   y-angle=-0.6273
       x-scale= 1.0020   y-scale= 1.0082   z-scale= 0.9999
     y/x-shear= 0.0034 z/x-shear=-0.0040 z/y-shear=-0.0259
 + - Fine net CPU time = 0.0 s
++ Computing output image
++ image warp: parameters = 0.6046 -0.6577 4.4844 -0.4943 -1.2690 -0.6273 1.0020 1.0082 0.9999 0.0034 -0.0040 -0.0259
++ Output dataset ./__tt_Sag3DMPRAGEs002a1001_ns_ob_temp_al_junk+orig.BRIK
++ Wrote -1Dmatrix_save ./Sag3DMPRAGEs002a1001_al_junk_e2a_only_mat.aff12.1D
++ 3dAllineate: total CPU time = 0.0 sec  Elapsed = 37.5
++ ###########################################################
++ #   Please check results visually for alignment quality   #
++ ###########################################################
++ #   '-autoweight' is recommended when using -lpc or -lpa  #
++ #   If your results are not good, please try again.       #
++ ###########################################################
#Script is running (command trimmed):
  cat_matvec -ONELINE ./Sag3DMPRAGEs002a1001_al_junk_e2a_only_mat.aff12.1D ./__tt_Sag3DMPRAGEs002a1001_ns_obla2e_mat.1D -I > ./Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D
#++ Combining anat to epi and oblique transformations
#Script is running (command trimmed):
  3dAllineate -base ./__tt_vr_base_ts_ns+orig -1Dmatrix_apply ./Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -prefix ./Sag3DMPRAGEs002a1001_al_junk -input ./__tt_Sag3DMPRAGEs002a1001_ns+orig -master BASE -mast_dxyz 1.000000 -weight_frac 1.0 -maxrot 6 -maxshf 10 -VERB -warp aff -source_automask+4 -twobest 11 -twopass -VERB -maxrot 45 -maxshf 40 -fineblur 1 -source_automask+2
++ 3dAllineate: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Registrator
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./__tt_vr_base_ts_ns+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./__tt_vr_base_ts_ns+orig.BRIK is 10.299996 degrees from plumb.
++ Source dataset: ./__tt_Sag3DMPRAGEs002a1001_ns+orig.HEAD
++ Base dataset:   ./__tt_vr_base_ts_ns+orig.HEAD
++ Loading datasets
 + Range param#4 [z-angle] = -6.000000 .. 6.000000
 + Range param#5 [x-angle] = -6.000000 .. 6.000000
 + Range param#6 [y-angle] = -6.000000 .. 6.000000
 + Range param#1 [x-shift] = -10.000000 .. 10.000000
 + Range param#2 [y-shift] = -10.000000 .. 10.000000
 + Range param#3 [z-shift] = -10.000000 .. 10.000000
 + Range param#4 [z-angle] = -45.000000 .. 45.000000
 + Range param#5 [x-angle] = -45.000000 .. 45.000000
 + Range param#6 [y-angle] = -45.000000 .. 45.000000
 + Range param#1 [x-shift] = -40.000000 .. 40.000000
 + Range param#2 [y-shift] = -40.000000 .. 40.000000
 + Range param#3 [z-shift] = -40.000000 .. 40.000000
++ changing output grid spacing to 1.0000 mm
++ OpenMP thread count = 6
++ ========== Applying transformation to 1 sub-bricks ==========
++ ========== sub-brick #0 ========== [total CPU to here=0.0 s]
 + * Enter alignment setup routine
 + - copying base image
 + - copying source image
 + - no weight image
 + - using 11 points from base image [use_all=0]
 + * Exit alignment setup routine
++ using -1Dmatrix_apply
++ Computing output image
++ image warp: parameters = 0.0092 -0.9910 0.1569 225.5536 -0.0169 0.1839 0.9880 72.6087 -1.0019 -0.0084 -0.0110 202.7800
++ Output dataset ./Sag3DMPRAGEs002a1001_al_junk+orig.BRIK
++ 3dAllineate: total CPU time = 0.0 sec  Elapsed = 1.1
++ ###########################################################
#++ Creating final output: skullstripped anat data
copying from dataset /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/__tt_Sag3DMPRAGEs002a1001_ns+orig to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig
#Script is running (command trimmed):
  3dcopy ./__tt_Sag3DMPRAGEs002a1001_ns+orig Sag3DMPRAGEs002a1001_ns
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ Creating final output: anat data aligned to epi
# copy is not necessary
#++ Saving history
#Script is running (command trimmed):
  3dNotes -h "align_epi_anat.py -anat2epi -anat Sag3DMPRAGEs002a1001+orig \
 -save_skullstrip -suffix _al_junk -epi vr_base+orig -epi_base 0 \
 -epi_strip 3dAutomask -giant_move -volreg off -tshift off" \
 ./Sag3DMPRAGEs002a1001_al_junk+orig

#++ Removing all the temporary files
#Script is running:
  \rm -f ./__tt_vr_base*
#Script is running:
  \rm -f ./__tt_Sag3DMPRAGEs002a1001*

# Finished alignment successfully

auto_warp.py -base MNI152_T1_2009c+tlrc -input Sag3DMPRAGEs002a1001_ns+orig -skull_strip_input no
#++ auto_warp.py version: 0.03
# Output directory /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/awpy/
#Script is running (command trimmed):
  mkdir ./awpy/
cd /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/awpy/
#Script is running (command trimmed):
  3dcopy /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig ./anat.nii
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#Script is running (command trimmed):
  3dUnifize -GM -input ./anat.nii -prefix ./anat.un.nii
++ 3dUnifize: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
 + Pre-processing: ADV.....UWG
++ Output dataset ./anat.un.nii
++ ===== Elapsed = 26.4 sec
#Script is running (command trimmed):
  3dcopy /usr/local/apps/afni/current/linux_openmp_64/MNI152_T1_2009c+tlrc ./base.nii
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ Aligning /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/awpy/base.nii data to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/awpy/anat.un.nii data
#Script is running (command trimmed):
  @auto_tlrc -base ./base.nii -input ./anat.un.nii -suffix .aff -no_ss -no_pre -init_xform CENTER 
Copying NIFTI volume to ./anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]

Performing center alignment with @Align_Centers

++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset ./anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig
 + deoblique
++ 3drefit processed 1 datasets
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ THD_rename_dataset_files: rename anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.HEAD -> __ats_tmp__anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.HEAD
++ THD_rename_dataset_files: rename anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.BRIK.gz -> __ats_tmp__anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.BRIK.gz
** THD_rename_dataset_files: old header anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+acpc.HEAD doesn't exist!
** THD_rename_dataset_files: old header anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+tlrc.HEAD doesn't exist!
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
Center distance of 0.000000 mm
Padding ...
++ 3dZeropad: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ output dataset: ./__ats_tmp__ref_base.nii_40pad+tlrc.BRIK
Resampling ...
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
Clipping -0.000100 2109.160100 ...
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___rs_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+tlrc.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp__resamp_NN+tlrc.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp__resamp_edge_art+tlrc.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
Registration (linear final interpolation) ...
++ 3dWarpDrive: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
RMS[0] = 123.405 62.1814   ITER = 12/137
123.405

Warping has converged.

++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
Applying brain mask
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ THD_rename_dataset_files: rename __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.HEAD -> __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff.skl+orig.HEAD
++ THD_rename_dataset_files: rename __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.BRIK.gz -> __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff.skl+orig.BRIK.gz
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
Unpadding ...
++ 3dZeropad: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ output dataset: ./__ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.BRIK
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig
[7m*+ WARNING:[0m Changing the space of an ORIG view dataset may cause confusion!
[7m*+ WARNING:[0m  NIFTI copies will be interpreted as TLRC view (not TLRC space).
[7m*+ WARNING:[0m  Consider changing the view of the dataset to TLRC view also
++ 3drefit processed 1 datasets
Changing view of transformed anatomy
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
Setting parent with 3drefit -wset ./anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.HEAD __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+tlrc
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+tlrc
 + setting Warp parent
++ 3drefit processed 1 datasets
++ 3dAFNItoNIFTI: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
Cleanup ...
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Warning: ignoring +orig on new_prefix.
++ THD_rename_dataset_files: rename __ats_tmp___rs_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.HEAD -> __ats_tmp___rs_pre.anat.un+orig.HEAD
++ THD_rename_dataset_files: rename __ats_tmp___rs_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.BRIK.gz -> __ats_tmp___rs_pre.anat.un+orig.BRIK.gz
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Warning: ignoring +orig on new_prefix.
++ THD_rename_dataset_files: rename pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.HEAD -> pre.anat.un+orig.HEAD
++ THD_rename_dataset_files: rename pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.BRIK.gz -> pre.anat.un+orig.BRIK.gz
#Script is running (command trimmed):
  3dAttribute DELTA ./anat.un.aff.nii
#Script is running (command trimmed):
  3dAttribute DELTA ./base.nii
1.000000 1.000000
#Script is running (command trimmed):
  3dinfo -same_grid ./anat.un.aff.nii ./base.nii
#++ Aligning /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/awpy/base.nii data to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/awpy/anat.un.aff.nii data
#Script is running (command trimmed):
  3dQwarp -prefix ./anat.un.aff.qw.nii -blur -3 -3 -workhard:0:1 -base ./base.nii -source ./anat.un.aff.nii 
++ OpenMP thread count = 6
++ 3dQwarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the (Hermite) Cubically Warped
++ Dataset zero-pad: xbot=0 xtop=0  ybot=1 ytop=2  zbot=15 ztop=0 voxels
++ Weightizing the base image
++ +++++++++++ Begin warp optimization:  base=./base.nii  source=./anat.un.aff.nii
++ AFNI warpomatic: 193 x 232 x 208 volume ; autobbox = 19..173 21..211 17..179 [clock= 13s 234ms]
lev=0 0..192 0..231 0..199: [first cost=-0.65973] ... done [cost:-0.65973==>-0.78740]
lev=1 patch=145x175x157 [clock= 33m 52s 167ms]........:[cost=-0.83347]:........ done [cost:-0.78740==>-0.83758 ; 16 patches optimized, 0 skipped]
lev=2 patch=109x131x117 [clock= 57m 49s 727ms]..................... done [cost:-0.83758==>-0.90417 ; 21 patches optimized, 6 skipped]
lev=3 patch=81x99x89 [clock= 1h 12m 16s 884ms]................. done [cost:-0.90417==>-0.97864 ; 41 patches optimized, 23 skipped]
lev=4 patch=61x73x67 [clock= 1h 25m 49s 25ms]................ done [cost:-0.97864==>-1.02454 ; 73 patches optimized, 52 skipped]
lev=5 patch=47x55x49 [clock= 1h 35m 54s 976ms].................. done [cost:-1.02454==>-1.10469 ; 193 patches optimized, 150 skipped]
lev=6 patch=35x41x37 [clock= 1h 46m 51s 141ms]........... done [cost:-1.10469==>-1.11860 ; 451 patches optimized, 359 skipped]
lev=7 patch=25x25x25 [clock= 1h 57m 50s 867ms]............................................ done [cost:-1.11860==>-1.23467 ; 1528 patches optimized, 1384 skipped]
++ ========== total number of parameters 'optimized' = 56049
++ Output dataset ./anat.un.aff.qw.nii
++ Output dataset ./anat.un.aff.qw_WARP.nii
++ ===== clock time = 2h 9m 45s 365ms
#++ Applying warps to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig
#Script is running (command trimmed):
  3dNwarpApply -nwarp "./anat.un.aff.qw_WARP.nii anat.un.aff.Xat.1D" -master ./base.nii -source /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig -prefix ./Sag3DMPRAGEs002a1001_ns.aw.nii 
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is './base.nii'
++ opened source dataset '/gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb9406/tb9406.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig'
++ Processing -nwarp 
++ Warping: .Z
++ Output dataset ./Sag3DMPRAGEs002a1001_ns.aw.nii
++ total Elapsed time = 22.6 sec
#++ Saving history
#Script is running (command trimmed):
  3dNotes -h "auto_warp.py -base MNI152_T1_2009c+tlrc -input \
 Sag3DMPRAGEs002a1001_ns+orig -skull_strip_input no" \
 ./Sag3DMPRAGEs002a1001_ns.aw.nii


3dbucket -prefix Sag3DMPRAGEs002a1001_ns awpy/Sag3DMPRAGEs002a1001_ns.aw.nii
++ 3dbucket: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
mv awpy/anat.un.aff.Xat.1D .
mv awpy/anat.un.aff.qw_WARP.nii .
if ( ! -f Sag3DMPRAGEs002a1001_ns+tlrc.HEAD ) then
foreach run ( 01 02 03 )
3dvolreg -verbose -zpad 1 -base vr_base+orig -1Dfile dfile.r01.1D -prefix rm.epi.volreg.r01 -cubic -1Dmatrix_save mat.r01.vr.aff12.1D pb02.tb9406.r01.tshift+orig
++ 3dvolreg: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./vr_base+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./vr_base+orig.BRIK is 10.299996 degrees from plumb.
++ Reading in base dataset ./vr_base+orig.BRIK
++ Oblique dataset:./pb02.tb9406.r01.tshift+orig.BRIK is 10.299996 degrees from plumb.
++ Reading input dataset ./pb02.tb9406.r01.tshift+orig.BRIK
++ Edging: x=3 y=3 z=2
++ Creating mask for -maxdisp
 + Automask has 31943 voxels
 + 5676 voxels left in -maxdisp mask after erosion
++ Initializing alignment base
++ Starting final pass on 150 sub-bricks: 0..1..2..3..4..5..6..7..8..9..10..11..12..13..14..15..16..17..18..19..20..21..22..23..24..25..26..27..28..29..30..31..32..33..34..35..36..37..38..39..40..41..42..43..44..45..46..47..48..49..50..51..52..53..54..55..56..57..58..59..60..61..62..63..64..65..66..67..68..69..70..71..72..73..74..75..76..77..78..79..80..81..82..83..84..85..86..87..88..89..90..91..92..93..94..95..96..97..98..99..100..101..102..103..104..105..106..107..108..109..110..111..112..113..114..115..116..117..118..119..120..121..122..123..124..125..126..127..128..129..130..131..132..133..134..135..136..137..138..139..140..141..142..143..144..145..146..147..148..149..
++ CPU time for realignment=0 s  [=0 s/sub-brick]
++ Min : roll=-0.018  pitch=-0.100  yaw=-0.105  dS=-0.039  dL=-0.017  dP=-0.022
++ Mean: roll=+0.022  pitch=-0.039  yaw=-0.033  dS=+0.218  dL=+0.045  dP=+0.045
++ Max : roll=+0.147  pitch=+0.077  yaw=+0.009  dS=+0.512  dL=+0.222  dP=+0.258
++ Max displacements (mm) for each sub-brick:
 0.00(0.00) 0.07(0.07) 0.13(0.17) 0.20(0.08) 0.24(0.04) 0.34(0.11) 0.32(0.02) 0.31(0.04) 0.38(0.08) 0.17(0.26) 0.22(0.19) 0.16(0.06) 0.09(0.06) 0.10(0.02) 0.08(0.03) 0.09(0.05) 0.10(0.05) 0.09(0.02) 0.08(0.03) 0.09(0.02) 0.09(0.04) 0.11(0.05) 0.09(0.03) 0.13(0.08) 0.11(0.03) 0.10(0.03) 0.09(0.02) 0.12(0.04) 0.14(0.04) 0.15(0.03) 0.15(0.03) 0.15(0.03) 0.17(0.04) 0.18(0.03) 0.15(0.04) 0.16(0.02) 0.19(0.06) 0.23(0.05) 0.21(0.03) 0.20(0.03) 0.20(0.02) 0.21(0.04) 0.23(0.05) 0.24(0.03) 0.23(0.03) 0.21(0.04) 0.16(0.05) 0.18(0.03) 0.23(0.05) 0.22(0.02) 0.22(0.02) 0.21(0.03) 0.20(0.04) 0.21(0.03) 0.20(0.04) 0.19(0.03) 0.22(0.04) 0.21(0.03) 0.21(0.02) 0.20(0.03) 0.23(0.03) 0.21(0.04) 0.28(0.08) 0.25(0.03) 0.27(0.03) 0.25(0.02) 0.22(0.05) 0.34(0.13) 0.39(0.07) 0.36(0.05) 0.39(0.04) 0.42(0.04) 0.44(0.04) 0.42(0.04) 0.40(0.02) 0.42(0.04) 0.43(0.06) 0.45(0.03) 0.42(0.04) 0.46(0.05) 0.44(0.02) 0.43(0.02) 0.49(0.07) 0.48(0.01) 0.48(0.03) 0.47(0.04) 0.48(0.02) 0.50(0.04) 0.50(0.04) 0.54(0.05) 0.53(0.02) 0.44(0.10) 0.36(0.10) 0.33(0.06) 0.36(0.05) 0.35(0.05) 0.35(0.02) 0.36(0.02) 0.39(0.04) 0.36(0.04) 0.35(0.05) 0.35(0.02) 0.39(0.06) 0.33(0.07) 0.34(0.03) 0.33(0.03) 0.36(0.06) 0.35(0.04) 0.33(0.04) 0.33(0.04) 0.36(0.05) 0.37(0.03) 0.36(0.02) 0.38(0.02) 0.40(0.07) 0.40(0.05) 0.40(0.07) 0.43(0.03) 0.40(0.04) 0.35(0.07) 0.39(0.05) 0.40(0.03) 0.42(0.05) 0.42(0.03) 0.41(0.04) 0.40(0.03) 0.42(0.04) 0.41(0.04) 0.38(0.04) 0.41(0.04) 0.36(0.05) 0.41(0.06) 0.62(0.22) 0.63(0.07) 0.66(0.05) 0.70(0.05) 0.66(0.04) 0.65(0.03) 0.67(0.03) 0.67(0.03) 0.65(0.03) 0.63(0.07) 0.61(0.09) 0.63(0.17) 0.64(0.04) 0.66(0.08) 0.65(0.06) 0.66(0.10) 0.74(0.11) 0.75(0.13)
++ Max displacement in automask = 0.75 (mm) at sub-brick 149
++ Max delta displ  in automask = 0.26 (mm) at sub-brick 9
++ Wrote dataset to disk in ./rm.epi.volreg.r01+orig.BRIK
3dcalc -overwrite -a pb02.tb9406.r01.tshift+orig -expr 1 -prefix rm.epi.all1
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
[7m*+ WARNING:[0m input 'a' is not used in the expression
cat_matvec -ONELINE anat.un.aff.Xat.1D Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -I mat.r01.vr.aff12.1D
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source pb02.tb9406.r01.tshift+orig -nwarp anat.un.aff.qw_WARP.nii mat.r01.warp.aff12.1D -prefix rm.epi.nomask.r01
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb02.tb9406.r01.tshift+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb02.tb9406.r01.tshift+orig.BRIK is 10.299996 degrees from plumb.
++ opened source dataset 'pb02.tb9406.r01.tshift+orig'
++ Processing -nwarp 
++ Warping: ......................................Z
++ Output dataset ./rm.epi.nomask.r01+tlrc.BRIK
++ total Elapsed time = 578.5 sec
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp anat.un.aff.qw_WARP.nii mat.r01.warp.aff12.1D -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r01
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./rm.epi.all1+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./rm.epi.all1+orig.BRIK is 10.299996 degrees from plumb.
++ opened source dataset 'rm.epi.all1+orig'
3dTstat -min -prefix rm.epi.min.r01 rm.epi.1.r01+tlrc
++ 3dTstat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: KR Hammett & RW Cox
end
3dvolreg -verbose -zpad 1 -base vr_base+orig -1Dfile dfile.r02.1D -prefix rm.epi.volreg.r02 -cubic -1Dmatrix_save mat.r02.vr.aff12.1D pb02.tb9406.r02.tshift+orig
++ 3dvolreg: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./vr_base+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./vr_base+orig.BRIK is 10.299996 degrees from plumb.
++ Reading in base dataset ./vr_base+orig.BRIK
++ Oblique dataset:./pb02.tb9406.r02.tshift+orig.BRIK is 10.299996 degrees from plumb.
++ Reading input dataset ./pb02.tb9406.r02.tshift+orig.BRIK
++ Edging: x=3 y=3 z=2
++ Creating mask for -maxdisp
 + Automask has 31844 voxels
 + 5619 voxels left in -maxdisp mask after erosion
++ Initializing alignment base
++ Starting final pass on 150 sub-bricks: 0..1..2..3..4..5..6..7..8..9..10..11..12..13..14..15..16..17..18..19..20..21..22..23..24..25..26..27..28..29..30..31..32..33..34..35..36..37..38..39..40..41..42..43..44..45..46..47..48..49..50..51..52..53..54..55..56..57..58..59..60..61..62..63..64..65..66..67..68..69..70..71..72..73..74..75..76..77..78..79..80..81..82..83..84..85..86..87..88..89..90..91..92..93..94..95..96..97..98..99..100..101..102..103..104..105..106..107..108..109..110..111..112..113..114..115..116..117..118..119..120..121..122..123..124..125..126..127..128..129..130..131..132..133..134..135..136..137..138..139..140..141..142..143..144..145..146..147..148..149..
++ CPU time for realignment=0 s  [=0 s/sub-brick]
++ Min : roll=+0.123  pitch=+0.764  yaw=+0.683  dS=+0.449  dL=+0.947  dP=-0.332
++ Mean: roll=+0.192  pitch=+1.084  yaw=+0.816  dS=+0.880  dL=+1.004  dP=-0.252
++ Max : roll=+0.210  pitch=+1.284  yaw=+0.918  dS=+0.985  dL=+1.145  dP=-0.180
++ Max displacements (mm) for each sub-brick:
 2.70(0.00) 2.60(0.20) 2.63(0.04) 2.69(0.09) 2.79(0.17) 2.92(0.56) 2.93(0.13) 2.89(0.05) 2.87(0.04) 2.91(0.07) 2.92(0.10) 2.89(0.06) 2.90(0.02) 2.89(0.03) 2.86(0.04) 2.86(0.03) 2.86(0.02) 2.85(0.04) 2.91(0.10) 2.91(0.03) 2.90(0.03) 2.90(0.04) 2.92(0.07) 2.93(0.04) 2.93(0.02) 2.94(0.03) 2.92(0.03) 2.91(0.03) 2.90(0.02) 2.93(0.03) 2.94(0.03) 2.91(0.06) 2.94(0.04) 2.95(0.03) 2.95(0.03) 2.94(0.04) 2.95(0.04) 2.96(0.01) 2.93(0.05) 2.93(0.03) 2.94(0.02) 2.94(0.04) 2.94(0.03) 2.98(0.05) 2.96(0.03) 2.95(0.03) 2.95(0.05) 2.97(0.03) 2.96(0.05) 2.95(0.04) 2.93(0.04) 2.92(0.07) 2.94(0.02) 2.94(0.02) 2.96(0.04) 2.96(0.04) 2.95(0.05) 2.95(0.07) 2.92(0.04) 2.91(0.02) 2.91(0.04) 2.94(0.03) 2.93(0.03) 2.91(0.07) 2.94(0.05) 2.95(0.08) 2.94(0.05) 2.97(0.03) 2.97(0.03) 2.97(0.05) 2.99(0.02) 2.96(0.03) 2.95(0.02) 2.96(0.02) 2.96(0.02) 2.96(0.02) 2.98(0.04) 3.00(0.02) 2.98(0.07) 2.97(0.03) 2.97(0.07) 2.99(0.05) 3.00(0.02) 2.99(0.06) 2.99(0.03) 3.00(0.04) 3.00(0.03) 3.01(0.03) 3.01(0.02) 3.02(0.05) 3.01(0.02) 3.04(0.06) 3.03(0.07) 3.03(0.09) 3.02(0.06) 3.01(0.05) 3.04(0.06) 3.02(0.03) 3.03(0.04) 3.04(0.07) 3.03(0.05) 3.05(0.03) 3.10(0.06) 3.11(0.03) 3.09(0.04) 3.08(0.02) 3.11(0.06) 3.11(0.04) 3.10(0.04) 3.13(0.04) 3.12(0.09) 3.10(0.02) 3.11(0.04) 3.15(0.06) 3.15(0.05) 3.14(0.08) 3.17(0.06) 3.20(0.04) 3.17(0.03) 3.19(0.04) 3.22(0.04) 3.21(0.09) 3.22(0.05) 3.19(0.04) 3.21(0.06) 3.24(0.05) 3.25(0.05) 3.26(0.02) 3.26(0.03) 3.28(0.02) 3.28(0.04) 3.29(0.05) 3.28(0.04) 3.29(0.07) 3.29(0.03) 3.33(0.07) 3.37(0.09) 3.31(0.07) 3.28(0.11) 3.30(0.05) 3.33(0.05) 3.34(0.15) 3.35(0.07) 3.33(0.06) 3.34(0.04) 3.38(0.07) 3.18(0.34) 2.82(0.47) 2.77(0.22) 2.76(0.17)
++ Max displacement in automask = 3.38 (mm) at sub-brick 145
++ Max delta displ  in automask = 0.56 (mm) at sub-brick 5
++ Wrote dataset to disk in ./rm.epi.volreg.r02+orig.BRIK
3dcalc -overwrite -a pb02.tb9406.r02.tshift+orig -expr 1 -prefix rm.epi.all1
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
[7m*+ WARNING:[0m input 'a' is not used in the expression
cat_matvec -ONELINE anat.un.aff.Xat.1D Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -I mat.r02.vr.aff12.1D
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source pb02.tb9406.r02.tshift+orig -nwarp anat.un.aff.qw_WARP.nii mat.r02.warp.aff12.1D -prefix rm.epi.nomask.r02
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb02.tb9406.r02.tshift+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb02.tb9406.r02.tshift+orig.BRIK is 10.299996 degrees from plumb.
++ opened source dataset 'pb02.tb9406.r02.tshift+orig'
++ Processing -nwarp 
++ Warping: ......................................Z
++ Output dataset ./rm.epi.nomask.r02+tlrc.BRIK
++ total Elapsed time = 581.3 sec
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp anat.un.aff.qw_WARP.nii mat.r02.warp.aff12.1D -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r02
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./rm.epi.all1+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./rm.epi.all1+orig.BRIK is 10.299996 degrees from plumb.
++ opened source dataset 'rm.epi.all1+orig'
3dTstat -min -prefix rm.epi.min.r02 rm.epi.1.r02+tlrc
++ 3dTstat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: KR Hammett & RW Cox
end
3dvolreg -verbose -zpad 1 -base vr_base+orig -1Dfile dfile.r03.1D -prefix rm.epi.volreg.r03 -cubic -1Dmatrix_save mat.r03.vr.aff12.1D pb02.tb9406.r03.tshift+orig
++ 3dvolreg: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./vr_base+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./vr_base+orig.BRIK is 10.299996 degrees from plumb.
++ Reading in base dataset ./vr_base+orig.BRIK
++ Oblique dataset:./pb02.tb9406.r03.tshift+orig.BRIK is 10.299996 degrees from plumb.
++ Reading input dataset ./pb02.tb9406.r03.tshift+orig.BRIK
++ Edging: x=3 y=3 z=2
++ Creating mask for -maxdisp
 + Automask has 31396 voxels
 + 5547 voxels left in -maxdisp mask after erosion
++ Initializing alignment base
++ Starting final pass on 150 sub-bricks: 0..1..2..3..4..5..6..7..8..9..10..11..12..13..14..15..16..17..18..19..20..21..22..23..24..25..26..27..28..29..30..31..32..33..34..35..36..37..38..39..40..41..42..43..44..45..46..47..48..49..50..51..52..53..54..55..56..57..58..59..60..61..62..63..64..65..66..67..68..69..70..71..72..73..74..75..76..77..78..79..80..81..82..83..84..85..86..87..88..89..90..91..92..93..94..95..96..97..98..99..100..101..102..103..104..105..106..107..108..109..110..111..112..113..114..115..116..117..118..119..120..121..122..123..124..125..126..127..128..129..130..131..132..133..134..135..136..137..138..139..140..141..142..143..144..145..146..147..148..149..
++ CPU time for realignment=0 s  [=0 s/sub-brick]
++ Min : roll=-0.050  pitch=-1.590  yaw=+1.102  dS=+3.875  dL=+1.823  dP=-0.161
++ Mean: roll=+0.052  pitch=-0.849  yaw=+1.163  dS=+4.268  dL=+1.880  dP=+0.005
++ Max : roll=+0.098  pitch=-0.387  yaw=+1.326  dS=+4.563  dL=+1.993  dP=+0.317
++ Max displacements (mm) for each sub-brick:
 7.50(0.00) 7.86(0.38) 7.66(0.22) 7.42(0.28) 7.30(0.19) 7.35(0.09) 7.40(0.16) 7.28(0.14) 7.26(0.07) 7.17(0.15) 7.07(0.14) 7.11(0.08) 7.07(0.06) 7.04(0.04) 6.97(0.09) 6.91(0.07) 6.88(0.10) 6.86(0.07) 6.80(0.11) 6.82(0.04) 6.79(0.06) 6.90(0.12) 6.92(0.05) 6.88(0.06) 6.84(0.06) 6.88(0.04) 6.88(0.02) 6.86(0.02) 6.80(0.08) 6.87(0.09) 6.84(0.05) 6.82(0.02) 6.80(0.03) 6.78(0.07) 6.79(0.02) 6.78(0.05) 6.78(0.02) 6.77(0.05) 6.77(0.03) 6.80(0.06) 6.76(0.06) 6.66(0.14) 6.61(0.10) 6.52(0.11) 6.50(0.04) 6.47(0.04) 6.41(0.10) 6.41(0.04) 6.39(0.06) 6.32(0.10) 6.29(0.07) 6.29(0.04) 6.30(0.09) 6.31(0.04) 6.25(0.08) 6.32(0.10) 6.31(0.04) 6.25(0.07) 6.29(0.05) 6.26(0.06) 6.27(0.04) 6.29(0.05) 6.25(0.04) 6.26(0.05) 6.26(0.05) 6.53(0.33) 6.62(0.12) 6.64(0.09) 6.64(0.03) 6.67(0.06) 6.65(0.04) 6.68(0.07) 6.64(0.05) 6.67(0.04) 6.68(0.04) 6.63(0.07) 6.65(0.07) 6.66(0.03) 6.66(0.05) 6.67(0.03) 6.66(0.04) 6.70(0.04) 6.69(0.04) 6.72(0.04) 6.63(0.11) 6.39(0.30) 6.19(0.26) 6.19(0.07) 6.16(0.05) 6.14(0.04) 6.17(0.04) 6.10(0.10) 6.25(0.21) 6.44(0.23) 6.43(0.06) 6.43(0.03) 6.41(0.06) 6.42(0.03) 6.41(0.04) 6.42(0.03) 6.41(0.03) 6.52(0.14) 6.41(0.15) 6.40(0.05) 6.39(0.11) 6.39(0.02) 6.40(0.04) 6.39(0.05) 6.37(0.06) 6.39(0.05) 6.39(0.03) 6.33(0.12) 6.31(0.07) 6.31(0.04) 6.32(0.05) 6.32(0.04) 6.33(0.03) 6.32(0.02) 6.34(0.04) 6.35(0.04) 6.36(0.03) 6.34(0.04) 6.34(0.03) 6.31(0.04) 6.30(0.05) 6.25(0.08) 6.26(0.04) 6.28(0.03) 6.26(0.05) 6.26(0.05) 6.33(0.07) 6.28(0.08) 6.25(0.04) 6.26(0.04) 6.22(0.07) 6.22(0.04) 6.22(0.04) 6.23(0.02) 6.24(0.04) 6.22(0.05) 6.23(0.03) 6.18(0.12) 6.12(0.11) 6.16(0.08) 6.13(0.14) 6.13(0.04) 6.19(0.11) 6.13(0.10) 5.72(0.43) 6.21(0.69)
++ Max displacement in automask = 7.86 (mm) at sub-brick 1
++ Max delta displ  in automask = 0.69 (mm) at sub-brick 149
++ Wrote dataset to disk in ./rm.epi.volreg.r03+orig.BRIK
3dcalc -overwrite -a pb02.tb9406.r03.tshift+orig -expr 1 -prefix rm.epi.all1
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
[7m*+ WARNING:[0m input 'a' is not used in the expression
cat_matvec -ONELINE anat.un.aff.Xat.1D Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -I mat.r03.vr.aff12.1D
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source pb02.tb9406.r03.tshift+orig -nwarp anat.un.aff.qw_WARP.nii mat.r03.warp.aff12.1D -prefix rm.epi.nomask.r03
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb02.tb9406.r03.tshift+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb02.tb9406.r03.tshift+orig.BRIK is 10.299996 degrees from plumb.
++ opened source dataset 'pb02.tb9406.r03.tshift+orig'
++ Processing -nwarp 
++ Warping: ......................................Z
*** Datablock write error: Write error in brick file: Is disk full, or write_protected?
++ Output dataset ./rm.epi.nomask.r03+tlrc.BRIK
++ total Elapsed time = 597.8 sec
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp anat.un.aff.qw_WARP.nii mat.r03.warp.aff12.1D -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r03
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./rm.epi.all1+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./rm.epi.all1+orig.BRIK is 10.299996 degrees from plumb.
++ opened source dataset 'rm.epi.all1+orig'
pigz: write error code 122
pigz: abort: write error on <stdout>

Fatal Signal 13 (SIGPIPE) received
     THD_nwarp_regrid
    IW3D_set_geometry_nwarp_catlist
   IW3D_read_nwarp_catlist
  3dNwarpApply
 Bottom of Debug Stack
** Command line was:
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp 'anat.un.aff.qw_WARP.nii mat.r03.warp.aff12.1D' -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r03
** AFNI version = AFNI_17.3.09  Compile date = Dec 22 2017
** [[Precompiled binary linux_openmp_64: Dec 22 2017]]
** Program Death **
** If you report this crash to the AFNI message board,
** please copy the error messages EXACTLY, and give
** the command line you used to run the program, and
** any other information needed to repeat the problem.
** You may later be asked to upload data to help debug.
** Crash log is appended to file /home/jangrawdc/.afni.crashlog
