% MakeClusterThreshMaskedStats_script.m
%
% Created 3/25/19 by DJ.

PRJDIR = "/data/NIMH_Haskins/a182_v2";


%% 1-grp Aud-Vis, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_1grp_minus12",[],...
    20,21,'aud-vis',[],'TEMP_AUD-VIS.tcsh');

%% 1-grp Aud+Vis, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_1grp_minus12",[],...
    14,15,'aud+vis',[],'TEMP_AUD+VIS.tcsh');

%% 1-grp Aud, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_1grp_minus12",[],...
    2,3,'aud',[],'TEMP_AUD.tcsh');

%% 1-grp Vis, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_1grp_minus12",[],...
    8,9,'vis',[],'TEMP_VIS.tcsh');



%% 2-grp Aud-Vis, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_2grp_minus12",[],...
    60,61,'aud-vis',[],'TEMP_AUD-VIS.tcsh');

%% 2-grp Aud+Vis, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_2grp_minus12",[],...
    42,43,'aud+vis',[],'TEMP_AUD+VIS.tcsh');

%% 2-grp Aud, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_2grp_minus12",[],...
    6,7,'aud',[],'TEMP_AUD.tcsh');

%% 2-grp Vis, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/GROUP_block_tlrc/",PRJDIR),...
    "ttest_allSubj_2grp_minus12",[],...
    24,25,'vis',[],'TEMP_VIS.tcsh');


%% 2-grp ISC top-bot, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/IscResults/Group/",PRJDIR),...
    "3dLME_2Grps_readScoreMedSplit_n69_Automask",[],...
    6,7,'top-bot',[],'TEMP_TOP-BOT.tcsh');

%% 2-grp ISC top-topbot, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/IscResults/Group/",PRJDIR),...
    "3dLME_2Grps_readScoreMedSplit_n69_Automask",[],...
    8,9,'top-topbot',[],'TEMP_TOP-TOPBOT.tcsh');

%% 2-grp ISC bot-topbot, p<0.01 alpha<0.05
SetUpClusterThreshMaskedStats(sprintf("%s/IscResults/Group/",PRJDIR),...
    "3dLME_2Grps_readScoreMedSplit_n69_Automask",[],...
    10,11,'bot-topbot',[],'TEMP_BOT-TOPBOT.tcsh');








