echo auto-generated by afni_proc.py, Tue Jan  2 15:40:59 2018
auto-generated by afni_proc.py, Tue Jan  2 15:40:59 2018
echo (version 6.02, December 12, 2017)
(version 6.02, December 12, 2017)
echo execution started: `date`
date
execution started: Tue Jan  2 15:40:59 EST 2018
afni -ver
Precompiled binary linux_openmp_64: Dec 22 2017 (Version AFNI_17.3.09)
afni_history -check_date 23 Sep 2016
-- is current: afni_history as new as: 23 Sep 2016
               most recent entry is:   22 Dec 2017
if ( 0 ) then
if ( 0 > 0 ) then
set subj = tb7001
endif
set output_dir = tb7001.srtt_v3
if ( -d tb7001.srtt_v3 ) then
set runs = ( `count -digits 2 1 3` )
count -digits 2 1 3
mkdir tb7001.srtt_v3
mkdir tb7001.srtt_v3/stimuli
cp stim_times/stim_times_srtt/bl1_c1_unstr.txt stim_times/stim_times_srtt/bl2_c1_unstr.txt stim_times/stim_times_srtt/bl3_c1_unstr.txt stim_times/stim_times_srtt/bl1_c2_str.txt stim_times/stim_times_srtt/bl2_c2_str.txt stim_times/stim_times_srtt/bl3_c2_str.txt tb7001.srtt_v3/stimuli
3dcopy anat/Sag3DMPRAGEs002a1001.nii.gz tb7001.srtt_v3/Sag3DMPRAGEs002a1001
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
3dTcat -prefix tb7001.srtt_v3/pb00.tb7001.r01.tcat func_srtt/ep2dbold156s004a001.nii.gz[6..$]
++ 3dTcat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ elapsed time = 1.5 s
3dTcat -prefix tb7001.srtt_v3/pb00.tb7001.r02.tcat func_srtt/ep2dbold156s006a001.nii.gz[6..$]
++ 3dTcat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ elapsed time = 1.2 s
3dTcat -prefix tb7001.srtt_v3/pb00.tb7001.r03.tcat func_srtt/ep2dbold156s008a001.nii.gz[6..$]
++ 3dTcat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ elapsed time = 1.5 s
set tr_counts = ( 150 150 150 )
cd tb7001.srtt_v3
touch out.pre_ss_warn.txt
foreach run ( 01 02 03 )
3dToutcount -automask -fraction -polort 3 -legendre pb00.tb7001.r01.tcat+orig
++ 3dToutcount: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb7001.r01.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb7001.r01.tcat+orig.BRIK is 12.699996 degrees from plumb.
++ 29676 voxels passed mask/clip
1deval -a outcount.r01.1D -expr 1-step(a-0.1)
if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
1deval -a outcount.r01.1D{0} -expr step(a-0.4)
end
3dToutcount -automask -fraction -polort 3 -legendre pb00.tb7001.r02.tcat+orig
++ 3dToutcount: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb7001.r02.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb7001.r02.tcat+orig.BRIK is 12.699996 degrees from plumb.
++ 29682 voxels passed mask/clip
1deval -a outcount.r02.1D -expr 1-step(a-0.1)
if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
1deval -a outcount.r02.1D{0} -expr step(a-0.4)
end
3dToutcount -automask -fraction -polort 3 -legendre pb00.tb7001.r03.tcat+orig
++ 3dToutcount: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb7001.r03.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb7001.r03.tcat+orig.BRIK is 12.699996 degrees from plumb.
++ 29651 voxels passed mask/clip
1deval -a outcount.r03.1D -expr 1-step(a-0.1)
if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
1deval -a outcount.r03.1D{0} -expr step(a-0.4)
end
cat outcount.r01.1D outcount.r02.1D outcount.r03.1D
cat rm.out.cen.r01.1D rm.out.cen.r02.1D rm.out.cen.r03.1D
foreach run ( 01 02 03 )
3dDespike -NEW -nomask -prefix pb01.tb7001.r01.despike pb00.tb7001.r01.tcat+orig
++ 3dDespike: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb7001.r01.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb7001.r01.tcat+orig.BRIK is 12.699996 degrees from plumb.
++ Input dataset is in short format, but output will be in float format
++ ignoring first 0 time points, using last 150
++ using 150 time points => -corder 5
++ Loading dataset pb00.tb7001.r01.tcat+orig
++ processing all 131072 voxels in dataset
++ Procesing time series with NEW model fit algorithm
++ smash edit thresholds: 3.1 .. 5.0 MADs
 +   [ 3.457% .. 0.072% of normal distribution]
 +   [ 8.839% .. 3.125% of Laplace distribution]
++ start OpenMP thread #2
++ start OpenMP thread #0
++ start OpenMP thread #5
++ start OpenMP thread #1
++ start OpenMP thread #3
++ start OpenMP thread #4
........................................................
++ Elapsed despike time =  1s 634ms

++ FINAL: 19353600 data points, 730954 edits [3.777%], 47040 big edits [0.243%]
++ Output dataset ./pb01.tb7001.r01.despike+orig.BRIK
end
3dDespike -NEW -nomask -prefix pb01.tb7001.r02.despike pb00.tb7001.r02.tcat+orig
++ 3dDespike: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb7001.r02.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb7001.r02.tcat+orig.BRIK is 12.699996 degrees from plumb.
++ Input dataset is in short format, but output will be in float format
++ ignoring first 0 time points, using last 150
++ using 150 time points => -corder 5
++ Loading dataset pb00.tb7001.r02.tcat+orig
++ processing all 131072 voxels in dataset
++ Procesing time series with NEW model fit algorithm
++ smash edit thresholds: 3.1 .. 5.0 MADs
 +   [ 3.457% .. 0.072% of normal distribution]
 +   [ 8.839% .. 3.125% of Laplace distribution]
++ start OpenMP thread #5
++ start OpenMP thread #2
++ start OpenMP thread #0
++ start OpenMP thread #1
++ start OpenMP thread #3
++ start OpenMP thread #4
........................................................
++ Elapsed despike time =  1s 606ms

++ FINAL: 19353600 data points, 735896 edits [3.802%], 51658 big edits [0.267%]
++ Output dataset ./pb01.tb7001.r02.despike+orig.BRIK
end
3dDespike -NEW -nomask -prefix pb01.tb7001.r03.despike pb00.tb7001.r03.tcat+orig
++ 3dDespike: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb00.tb7001.r03.tcat+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb00.tb7001.r03.tcat+orig.BRIK is 12.699996 degrees from plumb.
++ Input dataset is in short format, but output will be in float format
++ ignoring first 0 time points, using last 150
++ using 150 time points => -corder 5
++ Loading dataset pb00.tb7001.r03.tcat+orig
++ processing all 131072 voxels in dataset
++ Procesing time series with NEW model fit algorithm
++ smash edit thresholds: 3.1 .. 5.0 MADs
 +   [ 3.457% .. 0.072% of normal distribution]
 +   [ 8.839% .. 3.125% of Laplace distribution]
++ start OpenMP thread #2
++ start OpenMP thread #1
++ start OpenMP thread #0
++ start OpenMP thread #5
++ start OpenMP thread #3
++ start OpenMP thread #4
........................................................
++ Elapsed despike time =  1s 626ms

++ FINAL: 19353600 data points, 743988 edits [3.844%], 54048 big edits [0.279%]
++ Output dataset ./pb01.tb7001.r03.despike+orig.BRIK
end
foreach run ( 01 02 03 )
3dTshift -tzero 0 -quintic -prefix pb02.tb7001.r01.tshift -tpattern alt+z2 pb01.tb7001.r01.despike+orig
++ 3dTshift: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb01.tb7001.r01.despike+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb01.tb7001.r01.despike+orig.BRIK is 12.699996 degrees from plumb.
end
3dTshift -tzero 0 -quintic -prefix pb02.tb7001.r02.tshift -tpattern alt+z2 pb01.tb7001.r02.despike+orig
++ 3dTshift: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb01.tb7001.r02.despike+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb01.tb7001.r02.despike+orig.BRIK is 12.699996 degrees from plumb.
end
3dTshift -tzero 0 -quintic -prefix pb02.tb7001.r03.tshift -tpattern alt+z2 pb01.tb7001.r03.despike+orig
++ 3dTshift: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb01.tb7001.r03.despike+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb01.tb7001.r03.despike+orig.BRIK is 12.699996 degrees from plumb.
end
3dbucket -prefix vr_base pb02.tb7001.r01.tshift+orig[0]
++ 3dbucket: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
align_epi_anat.py -anat2epi -anat Sag3DMPRAGEs002a1001+orig -save_skullstrip -suffix _al_junk -epi vr_base+orig -epi_base 0 -epi_strip 3dAutomask -giant_move -volreg off -tshift off
#++ align_epi_anat version: 1.57
#++ turning off volume registration
#Script is running (command trimmed):
  3dAttribute DELTA ./vr_base+orig
#Script is running (command trimmed):
  3dAttribute DELTA ./vr_base+orig
#Script is running (command trimmed):
  3dAttribute DELTA ./Sag3DMPRAGEs002a1001+orig
#++ Multi-cost is lpc
#++ Removing all the temporary files
#Script is running:
  \rm -f ./__tt_vr_base*
#Script is running:
  \rm -f ./__tt_Sag3DMPRAGEs002a1001*
#Script is running (command trimmed):
  3dcopy ./Sag3DMPRAGEs002a1001+orig ./__tt_Sag3DMPRAGEs002a1001+orig
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ Removing skull from anat data
#Script is running (command trimmed):
  3dSkullStrip -orig_vol -input ./__tt_Sag3DMPRAGEs002a1001+orig -prefix ./__tt_Sag3DMPRAGEs002a1001_ns
Warning 3dSkullStrip:****************
 Surface self intersecting! trying again:
 smoothing of 84, avoid_vent -1
#Script is running (command trimmed):
  3dinfo ./__tt_Sag3DMPRAGEs002a1001_ns+orig | \grep 'Data Axes Tilt:'|\grep 'Oblique'
#++ Dataset /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/__tt_Sag3DMPRAGEs002a1001_ns+orig is not oblique
#Script is running (command trimmed):
  3dinfo ./vr_base+orig | \grep 'Data Axes Tilt:'|\grep 'Oblique'
#++ Dataset /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/vr_base+orig is ***oblique****
#Script is running (command trimmed):
  3dAttribute DELTA ./__tt_Sag3DMPRAGEs002a1001_ns+orig
#++ Spacing for anat to oblique epi alignment is 1.000000
#++ Matching obliquity of anat to epi
#Script is running (command trimmed):
  3dWarp -verb -card2oblique ./vr_base+orig -prefix ./__tt_Sag3DMPRAGEs002a1001_ns_ob -newgrid 1.000000 ./__tt_Sag3DMPRAGEs002a1001_ns+orig | \grep -A 4 '# mat44 Obliquity Transformation ::' > ./__tt_Sag3DMPRAGEs002a1001_ns_obla2e_mat.1D
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
#++ using 0th sub-brick because only one found
#Script is running (command trimmed):
  3dbucket -prefix ./__tt_vr_base_ts ./vr_base+orig'[0]'
++ 3dbucket: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ removing skull or area outside brain
#Script is running (command trimmed):
  3dAutomask -apply_prefix ./__tt_vr_base_ts_ns ./__tt_vr_base_ts+orig
++ 3dAutomask: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Emperor Zhark
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./__tt_vr_base_ts+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./__tt_vr_base_ts+orig.BRIK is 12.699996 degrees from plumb.
++ Loading dataset ./__tt_vr_base_ts+orig
++ Forming automask
 + Fixed clip level = 388.138702
 + Used gradual clip level = 351.132935 .. 438.167511
 + Number voxels above clip level = 30063
 + Clustering voxels ...
 + Largest cluster has 29780 voxels
 + Clustering voxels ...
 + Largest cluster has 29335 voxels
 + Filled   324 voxels in small holes; now have 29659 voxels
 + Filled     1 voxels in large holes; now have 29660 voxels
 + Clustering voxels ...
 + Largest cluster has 29660 voxels
 + Clustering non-brain voxels ...
 + Clustering voxels ...
 + Largest cluster has 101412 voxels
 + Mask now has 29660 voxels
++ 29660 voxels in the mask [out of 131072: 22.63%]
++ first  12 x-planes are zero [from R]
++ last   12 x-planes are zero [from L]
++ first   6 y-planes are zero [from P]
++ last    7 y-planes are zero [from A]
++ first   0 z-planes are zero [from I]
++ last    0 z-planes are zero [from S]
++ applying mask to original data
++ Writing masked data
++ Output dataset ./__tt_vr_base_ts_ns+orig.BRIK
++ CPU time = 0.000000 sec
#++ Computing weight mask
#Script is running (command trimmed):
  3dBrickStat -automask -percentile 90.000000 1 90.000000 ./__tt_vr_base_ts_ns+orig
#++ Applying threshold of 970.291870 on /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/__tt_vr_base_ts_ns+orig
#Script is running (command trimmed):
  3dcalc -datum float -prefix ./__tt_vr_base_ts_ns_wt -a ./__tt_vr_base_ts_ns+orig -expr 'min(1,(a/970.291870))'
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ././__tt_vr_base_ts_ns_wt+orig.BRIK
#++ Aligning anat data to epi data
#Script is running (command trimmed):
  3dAllineate -lpc -wtprefix ./__tt_Sag3DMPRAGEs002a1001_ns_ob_al_junk_wtal -weight ./__tt_vr_base_ts_ns_wt+orig -source ./__tt_Sag3DMPRAGEs002a1001_ns_ob+orig -prefix ./__tt_Sag3DMPRAGEs002a1001_ns_ob_temp_al_junk -base ./__tt_vr_base_ts_ns+orig -cmass -1Dmatrix_save ./Sag3DMPRAGEs002a1001_al_junk_e2a_only_mat.aff12.1D -master BASE -mast_dxyz 1.000000 -weight_frac 1.0 -maxrot 6 -maxshf 10 -VERB -warp aff -source_automask+4 -twobest 11 -twopass -VERB -maxrot 45 -maxshf 40 -fineblur 1 -source_automask+2 
++ 3dAllineate: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Registrator
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./__tt_vr_base_ts_ns_wt+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./__tt_vr_base_ts_ns_wt+orig.BRIK is 12.699996 degrees from plumb.
++ Oblique dataset:./__tt_vr_base_ts_ns+orig.BRIK is 12.699996 degrees from plumb.
++ Source dataset: ./__tt_Sag3DMPRAGEs002a1001_ns_ob+orig.HEAD
++ Base dataset:   ./__tt_vr_base_ts_ns+orig.HEAD
++ Loading datasets
++ 1497227 voxels in -source_automask+2
++ Zero-pad: zbot=4 ztop=4
++ 29660 voxels [18.1%] in weight mask
++ Output dataset ./__tt_Sag3DMPRAGEs002a1001_ns_ob_al_junk_wtal+orig.BRIK
++ Number of points for matching = 29660
++ NOTE: base and source coordinate systems have different handedness
 +       Orientations: base=Left handed (RPI); source=Right handed (RAI)
++ Local correlation: blok type = 'RHDD(13.3763)'
++ base center of mass = 32.005 28.958 21.340 (index)
 + source center of mass = 86.140 167.224 164.015 (index)
 + source-target CM = -1.936 0.247 -7.086 (xyz)
 + center of mass shifts = -1.936 0.247 -7.086
++ shift param auto-range: -71.5..67.6 -69.3..69.8 -57.2..43.0
 + Range param#4 [z-angle] = -6.000000 .. 6.000000
 + Range param#5 [x-angle] = -6.000000 .. 6.000000
 + Range param#6 [y-angle] = -6.000000 .. 6.000000
 + Range param#1 [x-shift] = -11.935539 .. 8.064461
 + Range param#2 [y-shift] = -9.752846 .. 10.247154
 + Range param#3 [z-shift] = -17.085609 .. 2.914391
 + Range param#4 [z-angle] = -45.000000 .. 45.000000
 + Range param#5 [x-angle] = -45.000000 .. 45.000000
 + Range param#6 [y-angle] = -45.000000 .. 45.000000
 + Range param#1 [x-shift] = -41.935539 .. 38.064461
 + Range param#2 [y-shift] = -39.752846 .. 40.247154
 + Range param#3 [z-shift] = -47.085609 .. 32.914391
 + 12 free parameters
++ Normalized convergence radius = 0.000449
++ changing output grid spacing to 1.0000 mm
++ OpenMP thread count = 6
++ ======= Allineation of 1 sub-bricks using Local Pearson Correlation Signed =======
 + source mask has 1497227 [out of 16587824] voxels
 + base mask has 40639 [out of 163840] voxels
++ ========== sub-brick #0 ========== [total CPU to here=0.0 s]
++ *** Coarse pass begins ***
 + * Enter alignment setup routine
 + - copying base image
 + - copying source image
 + - Smoothing base; radius=4.00
 + - Smoothing source; radius=4.00
 + !source mask fill: ubot=69 usiz=196.5
 + - copying weight image
 + - using 29660 points from base image [use_all=2]
 + * Exit alignment setup routine
 + - Search for coarse starting parameters
 + 25820 total points stored in 243 'RHDD(13.9615)' bloks
 + - number of free params = 6
 + - Testing (64+61)*64 params:#oo-..o*[#10=-0.0233084] *-.--o*[#28=-0.0369509] *.o*[#92=-0.052344] *o-.-oo$+*[#4240=-0.0554586] *.+
 + - best 45 costs found:
    0 v=-0.055459: -17.92 -19.25 -12.81 -20.53   3.14  10.08  [rand]
    1 v=-0.052344: -28.60 -13.09   6.25 -15.00 -15.00  15.00  [grid]
    2 v=-0.043633:   2.14   6.47   0.71  -4.32 -22.85 -18.95  [rand]
    3 v=-0.040479: -15.27  26.91 -20.42 -15.00  30.00  15.00  [grid]
    4 v=-0.040336: -17.92  19.74  -1.36 -20.53   3.14  10.08  [rand]
    5 v=-0.039491: -17.92 -19.25 -12.81 -20.53  -3.14  10.08  [rand]
    6 v=-0.038977: -15.96 -15.47   7.58 -24.25 -37.55   4.41  [rand]
    7 v=-0.038761:  11.40 -13.09   6.25  15.00 -30.00 -15.00  [grid]
    8 v=-0.038554:  24.73 -13.09   6.25  15.00 -15.00 -15.00  [grid]
    9 v=-0.038171:  19.04 -28.13  25.16   3.65 -28.33 -14.78  [rand]
   10 v=-0.038047:  11.48 -22.44  24.25  -4.37 -20.12 -15.12  [rand]
   11 v=-0.036951: -15.27 -13.09   6.25 -15.00 -15.00  15.00  [grid]
   12 v=-0.035475: -17.92  19.74  -1.36 -20.53  -3.14  10.08  [rand]
   13 v=-0.035126: -24.79 -23.33   3.33  -5.91 -29.74  29.45  [rand]
   14 v=-0.034613: -29.07 -18.62  20.65  -5.55 -17.35  23.42  [rand]
   15 v=-0.034419: -15.27 -26.42   6.25  15.00 -30.00  30.00  [grid]
   16 v=-0.032803:  -6.01  -5.98   0.71   4.32 -22.85  18.95  [rand]
   17 v=-0.032731: -15.27 -13.09   6.25 -15.00 -30.00  15.00  [grid]
   18 v=-0.031499: -10.58 -20.19  10.39 -25.20 -18.50 -13.54  [rand]
   19 v=-0.031365:  11.40 -26.42   6.25 -30.00 -30.00 -15.00  [grid]
   20 v=-0.031074: -22.91 -28.13  25.16  -3.65 -28.33  14.78  [rand]
   21 v=-0.031047:   2.14   6.47   0.71   4.32 -22.85 -18.95  [rand]
   22 v=-0.030242:  11.40 -26.42   6.25  15.00 -30.00 -15.00  [grid]
   23 v=-0.029370: -33.78  12.04  -4.34  23.31   3.26  40.47  [rand]
   24 v=-0.029125: -15.96 -15.47   7.58 -24.25 -37.55  -4.41  [rand]
   25 v=-0.029121:  11.40 -26.42  19.58 -15.00 -15.00 -30.00  [grid]
   26 v=-0.028991: -18.79 -18.34   7.37 -19.57 -37.09  16.59  [rand]
   27 v=-0.028871: -15.36 -22.44  24.25  -4.37 -20.12  15.12  [rand]
   28 v=-0.028845:   2.14  -5.98   0.71  -4.32 -22.85 -18.95  [rand]
   29 v=-0.028500: -15.27  13.58 -33.75 -15.00  30.00  15.00  [grid]
   30 v=-0.028294:  11.40  26.91  19.58 -30.00  30.00 -15.00  [grid]
   31 v=-0.028056:  11.40 -26.42  19.58 -15.00 -30.00 -30.00  [grid]
   32 v=-0.028036: -28.60 -26.42   6.25 -15.00 -30.00  15.00  [grid]
   33 v=-0.027763: -28.60 -26.42   6.25 -15.00 -30.00  30.00  [grid]
   34 v=-0.027279: -28.24 -25.71  10.71 -15.82 -17.65  37.25  [rand]
   35 v=-0.027254:  11.40 -26.42   6.25 -15.00 -30.00 -30.00  [grid]
   36 v=-0.027183:  -6.01   6.47   0.71   4.32 -22.85  18.95  [rand]
   37 v=-0.027117: -15.96 -15.47 -21.75 -24.25  37.55  -4.41  [rand]
   38 v=-0.027053: -15.27 -13.09   6.25  30.00 -30.00  15.00  [grid]
   39 v=-0.026950: -28.60 -13.09  19.58 -30.00 -30.00  30.00  [grid]
   40 v=-0.026417:  -6.01   6.47   0.71  -4.32 -22.85 -18.95  [rand]
   41 v=-0.026323: -15.27 -26.42   6.25 -15.00 -30.00  15.00  [grid]
   42 v=-0.026209:  11.40  13.58 -33.75  15.00  30.00 -15.00  [grid]
   43 v=-0.026074:  11.40 -13.09  19.58  15.00 -15.00  15.00  [grid]
   44 v=-0.025626: -15.27  13.58 -20.42 -15.00  30.00  15.00  [grid]
*[#8011=-0.0567802] *[#8014=-0.0606935] *[#8015=-0.0633622] *[#8017=-0.0638453] *[#8018=-0.0655781] *[#8021=-0.066459] *[#8023=-0.0674898] *[#8024=-0.0682332] *[#8025=-0.0691832] *[#8031=-0.0695312] *[#8034=-0.0696027] *[#8036=-0.0697543] *[#8037=-0.0701463] *[#8039=-0.0710283] *[#8040=-0.0712619] *[#8041=-0.0717165] *[#8043=-0.0721341] *[#8045=-0.0724101] *[#8046=-0.0726406] *[#8048=-0.0726969] *[#8050=-0.0730203] *[#8051=-0.0730534] *[#8230=-0.0857644] *[#8237=-0.0879105] *[#8241=-0.0927777] *[#8243=-0.093065] *[#8244=-0.0939044] *[#8245=-0.0947665] *[#8246=-0.095926] *[#8247=-0.0962584] *[#8249=-0.0965516] *[#8250=-0.096708] *[#8253=-0.0967228] *[#8255=-0.0988468] *[#8569=-0.100405] *[#8570=-0.101514] *[#8571=-0.101718] *[#8574=-0.10427] *[#8575=-0.106566] *[#8578=-0.112395] *[#8580=-0.114059] *[#8581=-0.116407] *[#8582=-0.119894] *[#8583=-0.123502] *[#8584=-0.124779] *[#8585=-0.124896] *[#8588=-0.12722] *[#8589=-0.127994] *[#8590=-0.128039] *[#8592=-0.130476] *[#8593=-0.133595] *[#8594=-0.136248] *[#8595=-0.137689] *[#8598=-0.13987] *[#8599=-0.140747] *[#8600=-0.141538] *[#8601=-0.142467] *[#8604=-0.144256] *[#8606=-0.147049] *[#8607=-0.150361] *[#8608=-0.155597] *[#8609=-0.159106] *[#8610=-0.160932] *[#8612=-0.162635] *[#8614=-0.171441] *[#8615=-0.172805] *[#8616=-0.173481] *[#8617=-0.174349]  + - costs of the above after a little optimization:
    0 v=-0.073053: -19.35 -18.27 -12.44 -18.99   1.07   8.61  [rand]
    1 v=-0.064916: -27.22 -15.43   4.40 -15.11 -14.19  14.88  [grid]
    2 v=-0.058813:  -0.72   4.62   1.02  -7.34 -26.18 -17.09  [rand]
    3 v=-0.061321: -14.71  33.37 -18.51 -17.09  28.23  12.75  [grid]
    4 v=-0.098847: -12.83  11.68  -4.21 -11.87   6.27   9.10  [rand]
    5 v=-0.081214: -17.12 -17.26 -11.48 -15.84  -1.07   9.90  [rand]
    6 v=-0.057006: -17.33 -14.52   8.73 -24.28 -27.97   4.22  [rand]
    7 v=-0.044655:  11.04 -12.95  10.04  14.39 -29.12 -14.90  [grid]
    8 v=-0.091579:  13.19 -12.02   4.62  10.24 -11.96  -9.77  [grid]
    9 v=-0.055431:  19.81 -27.30  20.46   0.25 -29.11 -19.11  [rand]
   10 v=-0.051735:  10.26 -23.46  22.06  -5.53 -23.16 -17.63  [rand]
  *11 v=-0.174349:  -7.45 -12.94   5.52  -4.57 -12.31   3.14  [grid]
   12 v=-0.046975: -16.42  18.84  -3.44 -20.04  -3.50  11.17  [rand]
   13 v=-0.066686: -25.84 -31.17   7.27  -6.10 -29.23  23.43  [rand]
   14 v=-0.037570: -28.70 -15.12  20.54  -5.28 -17.12  23.26  [rand]
   15 v=-0.069602: -15.93 -27.18   9.54   4.95 -25.42  23.55  [grid]
   16 v=-0.053890:  -8.78 -10.58   2.70   2.28 -24.35  15.19  [rand]
   17 v=-0.049351: -15.89 -16.03   7.56  -7.56 -28.01  15.91  [grid]
   18 v=-0.139032:  -4.51 -18.33   9.86  -5.10 -18.76  -2.83  [rand]
   19 v=-0.042945:  11.98 -27.42   5.35 -36.80 -32.85 -15.92  [grid]
   20 v=-0.074485: -18.84 -28.56  15.35  -3.01 -27.81  14.50  [rand]
   21 v=-0.048726:  -0.49   2.19   0.28   0.39 -23.61 -16.20  [rand]
   22 v=-0.073992:   7.12 -33.34   7.62  15.05 -30.93   0.83  [grid]
   23 v=-0.049516: -31.03   7.16  -2.89  29.55   5.21  42.38  [rand]
   24 v=-0.038910: -12.79 -14.47   4.18 -26.05 -36.26  -6.64  [rand]
   25 v=-0.037330:  10.66 -29.72  19.01 -15.79 -15.83 -30.53  [grid]
   26 v=-0.054550: -17.46 -22.65  12.25 -11.60 -30.48  11.27  [rand]
   27 v=-0.052159: -20.04 -21.47  21.83  -5.79 -23.37  12.55  [rand]
   28 v=-0.053882:  -0.60  -5.72   6.60  -8.45 -23.46 -15.46  [rand]
   29 v=-0.070417: -14.47   7.47 -29.47 -17.11  30.04  13.83  [grid]
   30 v=-0.035952:  13.02  24.79  19.61 -30.53  30.93 -15.26  [grid]
   31 v=-0.042806:  10.57 -26.14  19.63 -14.15 -23.62 -29.35  [grid]
   32 v=-0.049796: -24.03 -25.40   6.74 -14.00 -27.62  17.08  [grid]
   33 v=-0.066177: -25.88 -30.24   7.25  -6.08 -28.93  23.48  [grid]
   34 v=-0.033380: -28.13 -26.10  10.90 -11.59 -17.43  37.42  [rand]
   35 v=-0.073956:   3.78 -33.35   7.87 -11.36 -26.66 -22.62  [grid]
   36 v=-0.064004:  -0.72  -0.92   2.01   3.03 -20.96   7.44  [rand]
   37 v=-0.030807: -16.28 -15.07 -19.10 -23.51  38.73  -4.18  [rand]
   38 v=-0.035929: -16.24 -12.61   7.19  34.79 -30.39  14.31  [grid]
   39 v=-0.032911: -23.54  -9.43  16.47 -33.17 -27.59  29.50  [grid]
   40 v=-0.058796:  -0.91   4.81   1.83  -8.68 -27.15 -17.53  [rand]
   41 v=-0.095259: -12.15 -29.50  11.59  -4.94 -30.25   9.63  [grid]
   42 v=-0.055028:  12.89  11.62 -27.87  15.27  30.70  -7.69  [grid]
   43 v=-0.050321:   6.66 -12.28  14.90  11.78 -10.34  10.49  [grid]
   44 v=-0.071053:  -9.67  14.79 -24.31 -13.59  28.61  10.26  [grid]
 + - save #11 for twobest
 + - save #18 for twobest
 + - save # 4 for twobest
 + - save #41 for twobest
 + - save # 8 for twobest
 + - save # 5 for twobest
 + - save #20 for twobest
 + - save #22 for twobest
 + - save #35 for twobest
 + - skip # 0 for twobest: too close to set # 5
 + - save #44 for twobest
 + - save #29 for twobest
 + - save #15 for twobest
 + - save #13 for twobest
 + - skip #33 for twobest: too close to set #13
 + - save # 1 for twobest
 + - save #36 for twobest
 + - save # 3 for twobest
 + - save # 2 for twobest
 + - skip #40 for twobest: too close to set # 2
 + - save # 6 for twobest
 + - save # 9 for twobest
 + - save #42 for twobest
 + - save #26 for twobest
 + - save #16 for twobest
 + - Coarse startup search net CPU time = 0.0 s
++ Start refinement #1 on 12 coarse parameter sets
 + * Enter alignment setup routine
 + - Smoothing base; radius=3.11
 + - Smoothing source; radius=3.11
 + !source mask fill: ubot=69 usiz=196.5
 + - retaining old weight image
 + - using 29660 points from base image [use_all=2]
 + * Exit alignment setup routine
 + 26067 total points stored in 265 'RHDD(13.7332)' bloks
*[#10015=-0.175719] *[#10016=-0.195023] *[#10017=-0.23379] *[#10020=-0.238679] *[#10021=-0.259885] *[#10024=-0.265343] *[#10027=-0.285944] *[#10028=-0.292526] *[#10029=-0.321206] *[#10030=-0.369871] *[#10031=-0.423891] *[#10034=-0.433] *[#10037=-0.44747] *[#10040=-0.464642] *[#10041=-0.469554] *[#10044=-0.474656] *[#10047=-0.485411] *[#10048=-0.494327] *[#10049=-0.498581] *[#10050=-0.499569] *[#10052=-0.500213] *[#10053=-0.506057] *[#10054=-0.512616] *[#10055=-0.514247] 
 + - param set #1 has cost=-0.514247
 + -- Parameters = -1.3001 -1.9049 1.0046 -1.0684 -3.6690 1.4158 0.9789 1.0252 1.0510 -0.0304 -0.0162 0.0071
 + - param set #2 has cost=-0.124477
 + -- Parameters = -3.2551 -15.2425 8.2008 -3.8189 -15.5634 -2.3874 1.0326 0.9987 0.9885 -0.0038 0.0003 -0.0085
 + - param set #3 has cost=-0.361613
 + -- Parameters = -1.9946 0.4906 1.5756 -1.1310 -6.6462 0.8231 0.9835 1.1414 0.9833 0.0061 0.0069 -0.0008
 + - param set #4 has cost=-0.075583
 + -- Parameters = -11.8434 -29.1767 11.2123 -6.0754 -27.8201 7.6248 0.9951 1.0079 1.0030 0.0016 0.0007 -0.0025
 + - param set #5 has cost=-0.225466
 + -- Parameters = -1.9599 -6.6346 3.3082 0.1216 -7.0886 1.6778 0.9858 1.0016 1.0122 -0.0041 -0.0059 0.0058
 + - param set #6 has cost=-0.075338
 + -- Parameters = -16.3261 -17.3236 -11.3899 -15.4905 -1.1484 9.8066 1.0016 1.0014 1.0005 0.0090 0.0001 0.0001
 + - param set #7 has cost=-0.055337
 + -- Parameters = -16.0697 -28.7967 15.0151 -6.4073 -28.4197 10.9557 1.0105 0.9904 1.0014 0.0072 -0.0136 0.0002
 + - param set #8 has cost=-0.086611
 + -- Parameters = 5.7216 -28.5205 6.3586 8.7758 -29.1184 -0.1256 1.0341 1.0200 0.9157 -0.0078 -0.0063 -0.0302
 + - param set #9 has cost=-0.069164
 + -- Parameters = 3.1783 -35.7498 7.4588 -12.9026 -29.9791 -20.9655 1.0214 1.0041 1.0102 0.0095 0.0057 0.0109
 + - param set #10 has cost=-0.070969
 + -- Parameters = -9.8524 13.6842 -22.9958 -13.6625 28.9742 9.0317 1.0290 1.0037 1.0042 0.0008 0.0022 -0.0041
 + - param set #11 has cost=-0.057817
 + -- Parameters = -14.3450 7.6114 -29.3268 -17.3411 29.9179 13.3450 1.0152 1.0022 1.0005 0.0013 -0.0007 -0.0016
*[#10955=-0.541602] *[#10961=-0.580522] *[#10967=-0.616693] *[#10971=-0.623576] *[#10972=-0.627438] *[#10973=-0.637641] *[#10974=-0.638294] *[#10975=-0.639989] *[#10976=-0.654225] *[#10977=-0.66415] *[#10979=-0.667387] *[#10982=-0.67628] *[#10983=-0.682255] *[#10984=-0.684974] *[#10991=-0.685868] *[#10993=-0.686332] *[#10994=-0.687716] *[#10998=-0.688373] *[#11000=-0.689363] *[#11001=-0.689826] *[#11002=-0.68991] 
 + - param set #12 has cost=-0.689910
 + -- Parameters = -0.6852 -1.2253 -0.9670 0.2927 -2.3505 0.3761 1.0086 1.0257 0.9875 0.0010 -0.0102 -0.0023
 + - sorting parameter sets by cost
 + -- scanning for distances from #1
 + --- dist(#2,#1) = 0.173 
 + --- dist(#3,#1) = 0.315 
 + --- dist(#4,#1) = 0.0676 
 + --- dist(#5,#1) = 0.175 
 + --- dist(#6,#1) = 0.341 
 + --- dist(#7,#1) = 0.349 
 + --- dist(#8,#1) = 0.201 
 + --- dist(#9,#1) = 0.348 
 + --- dist(#10,#1) = 0.432 
 + --- dist(#11,#1) = 0.359 
 + --- dist(#12,#1) = 0.345 
++ Start refinement #2 on 12 coarse parameter sets
 + * Enter alignment setup routine
 + - Smoothing base; radius=2.42
 + - Smoothing source; radius=2.42
 + !source mask fill: ubot=69 usiz=196.5
 + - retaining old weight image
 + - using 29660 points from base image [use_all=2]
 + * Exit alignment setup routine
 + 26386 total points stored in 275 'RHDD(13.5933)' bloks
 + - param set #1 has cost=-0.686625
 + -- Parameters = -0.6662 -1.6526 -0.9826 0.2801 -2.1929 0.3517 1.0045 1.0115 1.0029 0.0019 -0.0069 -0.0040
 + - param set #2 has cost=-0.634579
 + -- Parameters = -1.0775 -1.3905 -0.2837 -0.1726 -2.0275 0.8536 1.0126 1.0107 1.0309 -0.0203 -0.0233 -0.0002
 + - param set #3 has cost=-0.602155
 + -- Parameters = -0.8948 -1.8547 -0.6931 0.2077 -4.7564 0.7652 1.0217 1.0416 1.0094 0.0120 -0.0140 -0.0462
 + - param set #4 has cost=-0.503360
 + -- Parameters = -1.1645 -3.2925 -0.5431 -0.0289 -4.0886 1.4165 1.0196 0.9685 1.0297 0.0013 -0.0227 -0.0447
 + - param set #5 has cost=-0.362613
 + -- Parameters = 0.8352 -2.2549 -2.9355 1.6502 -2.9547 -2.2413 1.0403 1.0082 0.9327 -0.0114 -0.0001 -0.0688
 + - param set #6 has cost=-0.070197
 + -- Parameters = 5.6892 -28.3785 6.7234 8.1833 -29.5042 -0.3688 1.0375 1.0436 0.9163 -0.0058 -0.0052 -0.0313
 + - param set #7 has cost=-0.059737
 + -- Parameters = -11.8129 -29.0744 11.9987 -6.4441 -28.1367 6.9242 0.9924 1.0097 1.0020 0.0097 0.0036 -0.0011
 + - param set #8 has cost=-0.063602
 + -- Parameters = -15.7321 -17.4267 -10.3529 -15.9367 -0.9503 9.2995 1.0193 1.0075 1.0089 0.0219 -0.0036 -0.0048
 + - param set #9 has cost=-0.058769
 + -- Parameters = -10.0546 13.2885 -23.1189 -13.1350 29.1088 8.7369 1.0434 0.9991 0.9991 0.0022 0.0062 -0.0033
 + - param set #10 has cost=-0.056711
 + -- Parameters = 3.1793 -35.7504 7.4585 -12.8994 -29.9797 -20.9663 1.0214 1.0041 1.0102 0.0098 0.0055 0.0108
 + - param set #11 has cost=-0.044494
 + -- Parameters = -14.5004 7.5866 -29.4302 -17.4818 30.0087 13.4633 1.0158 1.0015 1.0032 0.0016 0.0066 -0.0029
 + - param set #12 has cost=-0.045881
 + -- Parameters = -15.6639 -28.6474 12.6945 -6.3851 -28.7140 10.7555 1.0098 0.9902 1.0005 0.0068 -0.0148 0.0002
 + - sorting parameter sets by cost
 + -- scanning for distances from #1
 + --- dist(#2,#1) = 0.1 
 + --- dist(#3,#1) = 0.19 
 + --- dist(#4,#1) = 0.183 
 + --- dist(#5,#1) = 0.292 
 + --- dist(#6,#1) = 0.334 
 + --- dist(#7,#1) = 0.197 
 + --- dist(#8,#1) = 0.343 
 + --- dist(#9,#1) = 0.348 
 + --- dist(#10,#1) = 0.426 
 + --- dist(#11,#1) = 0.337 
 + --- dist(#12,#1) = 0.358 
++ Start refinement #3 on 12 coarse parameter sets
 + * Enter alignment setup routine
 + - Smoothing base; radius=1.88
 + - Smoothing source; radius=1.88
 + !source mask fill: ubot=69 usiz=196.5
 + - retaining old weight image
 + - using 29660 points from base image [use_all=2]
 + * Exit alignment setup routine
 + 26756 total points stored in 287 'RHDD(13.5079)' bloks
 + - param set #1 has cost=-0.647683
 + -- Parameters = -0.6620 -1.5997 -1.0031 0.2301 -2.2897 0.2208 1.0071 1.0121 0.9999 -0.0008 -0.0040 -0.0053
 + - param set #2 has cost=-0.634524
 + -- Parameters = -0.6954 -1.4835 -0.7191 0.0649 -1.8371 0.3191 1.0053 1.0130 1.0169 -0.0081 -0.0078 0.0019
 + - param set #3 has cost=-0.624703
 + -- Parameters = -0.6079 -1.8904 -0.7855 0.3893 -4.1468 0.4611 1.0107 1.0155 1.0077 0.0028 -0.0099 -0.0426
 + - param set #4 has cost=-0.623737
 + -- Parameters = -0.7856 -1.9922 -0.9888 0.3969 -3.7430 0.9291 1.0101 1.0093 1.0078 0.0037 -0.0214 -0.0378
 + - param set #5 has cost=-0.542350
 + -- Parameters = -0.8891 -2.4060 -2.0399 0.1758 -6.0649 0.2269 1.0169 1.0097 0.9484 -0.0053 -0.0086 -0.0843
 + - param set #6 has cost=-0.064972
 + -- Parameters = 4.9685 -27.7949 6.2002 6.8049 -30.4972 -1.2368 1.0179 1.0694 0.8916 -0.0192 0.0015 -0.0327
 + - param set #7 has cost=-0.053370
 + -- Parameters = -15.6017 -17.3285 -10.4991 -15.7879 -0.6024 8.9519 1.0193 1.0073 1.0102 0.0225 -0.0018 0.0008
 + - param set #8 has cost=-0.057021
 + -- Parameters = -10.9052 -29.1423 12.4509 -6.0797 -28.2244 6.1649 0.9898 0.9987 0.9904 0.0129 0.0066 -0.0018
 + - param set #9 has cost=-0.048622
 + -- Parameters = -9.8375 13.0159 -22.5992 -13.1823 28.9930 8.6803 1.0439 0.9930 0.9916 0.0018 0.0065 -0.0010
 + - param set #10 has cost=-0.047059
 + -- Parameters = 3.3829 -35.7703 7.2529 -13.2080 -30.1115 -21.1916 1.0199 1.0038 1.0185 0.0097 0.0057 0.0104
 + - param set #11 has cost=-0.050901
 + -- Parameters = -13.2648 -28.3556 11.9417 -6.0879 -28.3155 8.5101 1.0125 1.0135 0.9991 0.0090 -0.0111 -0.0025
 + - param set #12 has cost=-0.037377
 + -- Parameters = -14.7071 7.3738 -29.3911 -17.4457 30.0003 13.4605 1.0200 1.0067 1.0044 0.0012 0.0090 -0.0020
 + - sorting parameter sets by cost
 + -- scanning for distances from #1
 + --- dist(#2,#1) = 0.0464 
 + --- dist(#3,#1) = 0.168 
 + --- dist(#4,#1) = 0.146 
 + --- dist(#5,#1) = 0.356 
 + --- dist(#6,#1) = 0.327 
 + --- dist(#7,#1) = 0.344 
 + --- dist(#8,#1) = 0.197 
 + --- dist(#9,#1) = 0.334 
 + --- dist(#10,#1) = 0.348 
 + --- dist(#11,#1) = 0.427 
 + --- dist(#12,#1) = 0.359 
 + - Total coarse refinement net CPU time = 0.0 s; 3211 funcs
++ *** Fine pass begins ***
 + * Enter alignment setup routine
 + - Smoothing base; radius=1.00
 + - Smoothing source; radius=1.00
 + !source mask fill: ubot=69 usiz=196.5
 + - retaining old weight image
 + * Exit alignment setup routine
++ Picking best parameter set out of 13 cases
 + 26745 total points stored in 288 'RHDD(13.4252)' bloks
 + - cost(#1)=-0.619223 *
 + -- Parameters = -0.6620 -1.5997 -1.0031 0.2301 -2.2897 0.2208 1.0071 1.0121 0.9999 -0.0008 -0.0040 -0.0053
 + - cost(#2)=-0.607335  
 + -- Parameters = -0.6954 -1.4835 -0.7191 0.0649 -1.8371 0.3191 1.0053 1.0130 1.0169 -0.0081 -0.0078 0.0019
 + - cost(#3)=-0.598317  
 + -- Parameters = -0.6079 -1.8904 -0.7855 0.3893 -4.1468 0.4611 1.0107 1.0155 1.0077 0.0028 -0.0099 -0.0426
 + - cost(#4)=-0.595133  
 + -- Parameters = -0.7856 -1.9922 -0.9888 0.3969 -3.7430 0.9291 1.0101 1.0093 1.0078 0.0037 -0.0214 -0.0378
 + - cost(#5)=-0.515259  
 + -- Parameters = -0.8891 -2.4060 -2.0399 0.1758 -6.0649 0.2269 1.0169 1.0097 0.9484 -0.0053 -0.0086 -0.0843
 + - cost(#6)=-0.061344  
 + -- Parameters = 4.9685 -27.7949 6.2002 6.8049 -30.4972 -1.2368 1.0179 1.0694 0.8916 -0.0192 0.0015 -0.0327
 + - cost(#7)=-0.053418  
 + -- Parameters = -10.9052 -29.1423 12.4509 -6.0797 -28.2244 6.1649 0.9898 0.9987 0.9904 0.0129 0.0066 -0.0018
 + - cost(#8)=-0.048705  
 + -- Parameters = -15.6017 -17.3285 -10.4991 -15.7879 -0.6024 8.9519 1.0193 1.0073 1.0102 0.0225 -0.0018 0.0008
 + - cost(#9)=-0.047440  
 + -- Parameters = -13.2648 -28.3556 11.9417 -6.0879 -28.3155 8.5101 1.0125 1.0135 0.9991 0.0090 -0.0111 -0.0025
 + - cost(#10)=-0.040199  
 + -- Parameters = -9.8375 13.0159 -22.5992 -13.1823 28.9930 8.6803 1.0439 0.9930 0.9916 0.0018 0.0065 -0.0010
 + - cost(#11)=-0.041196  
 + -- Parameters = 3.3829 -35.7703 7.2529 -13.2080 -30.1115 -21.1916 1.0199 1.0038 1.0185 0.0097 0.0057 0.0104
 + - cost(#12)=-0.031398  
 + -- Parameters = -14.7071 7.3738 -29.3911 -17.4457 30.0003 13.4605 1.0200 1.0067 1.0044 0.0012 0.0090 -0.0020
 + - cost(#13)=-0.039196  
 + -- Parameters = -1.9355 0.2472 -7.0856 0.0000 0.0000 0.0000 1.0000 1.0000 1.0000 0.0000 0.0000 0.0000
 + -num_rtb 99 ==> refine all 13 cases
 + - cost(#1)=-0.620025 *
 + -- Parameters = -0.6370 -1.6354 -0.9478 0.2437 -2.2286 0.1361 1.0072 1.0121 1.0014 -0.0008 -0.0035 -0.0053
 + - cost(#2)=-0.617584  
 + -- Parameters = -0.5905 -1.5650 -0.9932 0.2393 -1.9680 0.0645 1.0054 1.0127 1.0002 -0.0027 -0.0032 0.0002
 + - cost(#3)=-0.611866  
 + -- Parameters = -0.7086 -1.9110 -1.0570 0.1929 -3.6599 0.2318 1.0084 1.0125 0.9980 -0.0005 -0.0046 -0.0336
 + - cost(#4)=-0.607837  
 + -- Parameters = -0.8628 -1.9273 -1.1317 0.1428 -3.6098 0.6817 1.0077 1.0119 0.9948 -0.0029 -0.0149 -0.0325
 + - cost(#5)=-0.564418  
 + -- Parameters = -0.5865 -2.4022 -1.5034 0.2972 -5.4047 0.1170 0.9974 1.0080 0.9825 0.0000 -0.0019 -0.0724
 + - cost(#6)=-0.064738  
 + -- Parameters = 4.3351 -27.2734 6.4609 6.5560 -30.3430 -0.2887 1.0141 1.0768 0.8904 -0.0142 0.0121 -0.0280
 + - cost(#7)=-0.053792  
 + -- Parameters = -10.9640 -29.1795 12.5361 -6.2746 -28.1618 5.9536 0.9897 0.9977 0.9910 0.0124 0.0065 -0.0062
 + - cost(#8)=-0.049314  
 + -- Parameters = -15.5650 -17.3303 -10.4453 -15.8162 -0.5942 8.5827 1.0153 1.0109 1.0114 0.0231 -0.0016 -0.0019
 + - cost(#9)=-0.049612  
 + -- Parameters = -13.2847 -28.4442 11.8160 -6.2976 -28.1597 7.9576 1.0085 1.0067 0.9941 0.0099 -0.0035 -0.0109
 + - cost(#10)=-0.041342  
 + -- Parameters = -9.6724 12.9851 -22.3544 -13.2496 28.9978 6.9906 1.0421 0.9926 0.9951 0.0034 0.0081 -0.0001
 + - cost(#11)=-0.044718  
 + -- Parameters = 2.6615 -36.0152 7.4767 -13.5979 -29.8370 -20.2321 1.0158 1.0010 1.0130 0.0097 0.0088 0.0095
 + - cost(#12)=-0.032158  
 + -- Parameters = -14.9755 7.3152 -29.3653 -17.5882 29.9556 13.4753 1.0254 1.0062 1.0039 0.0015 0.0099 -0.0024
 + - cost(#13)=-0.619002  
 + -- Parameters = -0.6352 -1.6274 -0.9393 0.1177 -2.3895 0.0062 1.0059 1.0110 1.0011 -0.0063 -0.0004 -0.0084
 + - case #1 is now the best
 + - Initial  cost = -0.620025
 + - Initial fine Parameters = -0.6370 -1.6354 -0.9478 0.2437 -2.2286 0.1361 1.0072 1.0121 1.0014 -0.0008 -0.0035 -0.0053
 + - Finalish cost = -0.620881 ; 197 funcs
 + - Final    cost = -0.620891 ; 132 funcs
 + Final fine fit Parameters:
       x-shift=-0.5993   y-shift=-1.6605   z-shift=-0.9603
       z-angle= 0.2527   x-angle=-2.4220   y-angle=-0.0395
       x-scale= 1.0077   y-scale= 1.0121   z-scale= 1.0009
     y/x-shear=-0.0003 z/x-shear= 0.0006 z/y-shear=-0.0087
 + - Fine net CPU time = 0.0 s
++ Computing output image
++ image warp: parameters = -0.5993 -1.6605 -0.9603 0.2527 -2.4220 -0.0395 1.0077 1.0121 1.0009 -0.0003 0.0006 -0.0087
++ Output dataset ./__tt_Sag3DMPRAGEs002a1001_ns_ob_temp_al_junk+orig.BRIK
++ Wrote -1Dmatrix_save ./Sag3DMPRAGEs002a1001_al_junk_e2a_only_mat.aff12.1D
++ 3dAllineate: total CPU time = 0.0 sec  Elapsed = 32.9
++ ###########################################################
++ #   Please check results visually for alignment quality   #
++ ###########################################################
++ #   '-autoweight' is recommended when using -lpc or -lpa  #
++ #   If your results are not good, please try again.       #
++ ###########################################################
#Script is running (command trimmed):
  cat_matvec -ONELINE ./Sag3DMPRAGEs002a1001_al_junk_e2a_only_mat.aff12.1D ./__tt_Sag3DMPRAGEs002a1001_ns_obla2e_mat.1D -I > ./Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D
#++ Combining anat to epi and oblique transformations
#Script is running (command trimmed):
  3dAllineate -base ./__tt_vr_base_ts_ns+orig -1Dmatrix_apply ./Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -prefix ./Sag3DMPRAGEs002a1001_al_junk -input ./__tt_Sag3DMPRAGEs002a1001_ns+orig -master BASE -mast_dxyz 1.000000 -weight_frac 1.0 -maxrot 6 -maxshf 10 -VERB -warp aff -source_automask+4 -twobest 11 -twopass -VERB -maxrot 45 -maxshf 40 -fineblur 1 -source_automask+2
++ 3dAllineate: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Registrator
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./__tt_vr_base_ts_ns+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./__tt_vr_base_ts_ns+orig.BRIK is 12.699996 degrees from plumb.
++ Source dataset: ./__tt_Sag3DMPRAGEs002a1001_ns+orig.HEAD
++ Base dataset:   ./__tt_vr_base_ts_ns+orig.HEAD
++ Loading datasets
 + Range param#4 [z-angle] = -6.000000 .. 6.000000
 + Range param#5 [x-angle] = -6.000000 .. 6.000000
 + Range param#6 [y-angle] = -6.000000 .. 6.000000
 + Range param#1 [x-shift] = -10.000000 .. 10.000000
 + Range param#2 [y-shift] = -10.000000 .. 10.000000
 + Range param#3 [z-shift] = -10.000000 .. 10.000000
 + Range param#4 [z-angle] = -45.000000 .. 45.000000
 + Range param#5 [x-angle] = -45.000000 .. 45.000000
 + Range param#6 [y-angle] = -45.000000 .. 45.000000
 + Range param#1 [x-shift] = -40.000000 .. 40.000000
 + Range param#2 [y-shift] = -40.000000 .. 40.000000
 + Range param#3 [z-shift] = -40.000000 .. 40.000000
++ changing output grid spacing to 1.0000 mm
++ OpenMP thread count = 6
++ ========== Applying transformation to 1 sub-bricks ==========
++ ========== sub-brick #0 ========== [total CPU to here=0.0 s]
 + * Enter alignment setup routine
 + - copying base image
 + - copying source image
 + - no weight image
 + - using 11 points from base image [use_all=0]
 + * Exit alignment setup routine
++ using -1Dmatrix_apply
++ Computing output image
++ image warp: parameters = -0.0047 -0.9938 0.1782 232.0672 0.0008 0.1896 0.9853 51.7696 -1.0077 0.0045 -0.0007 199.2675
++ Output dataset ./Sag3DMPRAGEs002a1001_al_junk+orig.BRIK
++ 3dAllineate: total CPU time = 0.0 sec  Elapsed = 1.5
++ ###########################################################
#++ Creating final output: skullstripped anat data
copying from dataset /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/__tt_Sag3DMPRAGEs002a1001_ns+orig to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig
#Script is running (command trimmed):
  3dcopy ./__tt_Sag3DMPRAGEs002a1001_ns+orig Sag3DMPRAGEs002a1001_ns
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ Creating final output: anat data aligned to epi
# copy is not necessary
#++ Saving history
#Script is running (command trimmed):
  3dNotes -h "align_epi_anat.py -anat2epi -anat Sag3DMPRAGEs002a1001+orig \
 -save_skullstrip -suffix _al_junk -epi vr_base+orig -epi_base 0 \
 -epi_strip 3dAutomask -giant_move -volreg off -tshift off" \
 ./Sag3DMPRAGEs002a1001_al_junk+orig

#++ Removing all the temporary files
#Script is running:
  \rm -f ./__tt_vr_base*
#Script is running:
  \rm -f ./__tt_Sag3DMPRAGEs002a1001*

# Finished alignment successfully

auto_warp.py -base MNI152_T1_2009c+tlrc -input Sag3DMPRAGEs002a1001_ns+orig -skull_strip_input no
#++ auto_warp.py version: 0.03
# Output directory /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/awpy/
#Script is running (command trimmed):
  mkdir ./awpy/
cd /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/awpy/
#Script is running (command trimmed):
  3dcopy /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig ./anat.nii
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#Script is running (command trimmed):
  3dUnifize -GM -input ./anat.nii -prefix ./anat.un.nii
++ 3dUnifize: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
 + Pre-processing: ADV.....UWG
++ Output dataset ./anat.un.nii
++ ===== Elapsed = 26.6 sec
#Script is running (command trimmed):
  3dcopy /usr/local/apps/afni/current/linux_openmp_64/MNI152_T1_2009c+tlrc ./base.nii
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
#++ Aligning /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/awpy/base.nii data to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/awpy/anat.un.nii data
#Script is running (command trimmed):
  @auto_tlrc -base ./base.nii -input ./anat.un.nii -suffix .aff -no_ss -no_pre -init_xform CENTER 
Copying NIFTI volume to ./anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA
++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]

Performing center alignment with @Align_Centers

++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset ./anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig
 + deoblique
++ 3drefit processed 1 datasets
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ THD_rename_dataset_files: rename anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.HEAD -> __ats_tmp__anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.HEAD
++ THD_rename_dataset_files: rename anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.BRIK.gz -> __ats_tmp__anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+orig.BRIK.gz
** THD_rename_dataset_files: old header anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+acpc.HEAD doesn't exist!
** THD_rename_dataset_files: old header anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA_shft+tlrc.HEAD doesn't exist!
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
Center distance of 0.000000 mm
Padding ...
++ 3dZeropad: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ output dataset: ./__ats_tmp__ref_base.nii_40pad+tlrc.BRIK
Resampling ...
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
Clipping -0.000100 3468.670100 ...
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___rs_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+tlrc.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp__resamp_NN+tlrc.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp__resamp_edge_art+tlrc.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
Registration (linear final interpolation) ...
++ 3dWarpDrive: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
RMS[0] = 114.182 54.6803   ITER = 8/137
114.182

Warping has converged.

++ 3dcopy: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
Applying brain mask
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
++ 3dWarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ THD_rename_dataset_files: rename __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.HEAD -> __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff.skl+orig.HEAD
++ THD_rename_dataset_files: rename __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.BRIK.gz -> __ats_tmp___pad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff.skl+orig.BRIK.gz
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
Unpadding ...
++ 3dZeropad: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ output dataset: ./__ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.BRIK
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig
[7m*+ WARNING:[0m Changing the space of an ORIG view dataset may cause confusion!
[7m*+ WARNING:[0m  NIFTI copies will be interpreted as TLRC view (not TLRC space).
[7m*+ WARNING:[0m  Consider changing the view of the dataset to TLRC view also
++ 3drefit processed 1 datasets
Changing view of transformed anatomy
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+orig.HEAD
 + changing dataset view code
 + Changed dataset view type and filenames.
++ 3drefit processed 1 datasets
Setting parent with 3drefit -wset ./anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.HEAD __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+tlrc
++ 3drefit: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset __ats_tmp___upad40_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA.aff+tlrc
 + setting Warp parent
++ 3drefit processed 1 datasets
++ 3dAFNItoNIFTI: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
Cleanup ...
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Warning: ignoring +orig on new_prefix.
++ THD_rename_dataset_files: rename __ats_tmp___rs_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.HEAD -> __ats_tmp___rs_pre.anat.un+orig.HEAD
++ THD_rename_dataset_files: rename __ats_tmp___rs_pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.BRIK.gz -> __ats_tmp___rs_pre.anat.un+orig.BRIK.gz
++ 3drename: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Warning: ignoring +orig on new_prefix.
++ THD_rename_dataset_files: rename pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.HEAD -> pre.anat.un+orig.HEAD
++ THD_rename_dataset_files: rename pre.anat.un_AFN_OYmeqfZ3JqF7n9LNC7gDAA+orig.BRIK.gz -> pre.anat.un+orig.BRIK.gz
#Script is running (command trimmed):
  3dAttribute DELTA ./anat.un.aff.nii
#Script is running (command trimmed):
  3dAttribute DELTA ./base.nii
1.000000 1.000000
#Script is running (command trimmed):
  3dinfo -same_grid ./anat.un.aff.nii ./base.nii
#++ Aligning /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/awpy/base.nii data to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/awpy/anat.un.aff.nii data
#Script is running (command trimmed):
  3dQwarp -prefix ./anat.un.aff.qw.nii -blur -3 -3 -workhard:0:1 -base ./base.nii -source ./anat.un.aff.nii 
++ OpenMP thread count = 6
++ 3dQwarp: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the (Hermite) Cubically Warped
++ Dataset zero-pad: xbot=0 xtop=0  ybot=1 ytop=2  zbot=15 ztop=0 voxels
++ Weightizing the base image
++ +++++++++++ Begin warp optimization:  base=./base.nii  source=./anat.un.aff.nii
++ AFNI warpomatic: 193 x 232 x 208 volume ; autobbox = 19..173 21..211 17..179 [clock= 13s 67ms]
lev=0 0..192 0..231 0..199: [first cost=-0.82262] ... done [cost:-0.82262==>-0.88471]
lev=1 patch=145x175x157 [clock= 33m 24s 974ms]........:[cost=-0.90045]:........ done [cost:-0.88471==>-0.90246 ; 16 patches optimized, 0 skipped]
lev=2 patch=109x131x117 [clock= 52m 57s 796ms]..................... done [cost:-0.90246==>-0.95948 ; 21 patches optimized, 6 skipped]
lev=3 patch=81x99x89 [clock= 1h 7m 13s 973ms]............. done [cost:-0.95948==>-1.03200 ; 41 patches optimized, 23 skipped]
lev=4 patch=61x73x67 [clock= 1h 20m 45s 223ms]............... done [cost:-1.03200==>-1.10241 ; 73 patches optimized, 52 skipped]
lev=5 patch=47x55x49 [clock= 1h 31m 1s 758ms]............... done [cost:-1.10241==>-1.17229 ; 193 patches optimized, 150 skipped]
lev=6 patch=35x41x37 [clock= 1h 42m 5s 601ms]................. done [cost:-1.17229==>-1.23272 ; 451 patches optimized, 359 skipped]
lev=7 patch=25x25x25 [clock= 1h 53m 12s 970ms].............................. done [cost:-1.23272==>-1.33071 ; 1528 patches optimized, 1384 skipped]
++ ========== total number of parameters 'optimized' = 56049
++ Output dataset ./anat.un.aff.qw.nii
++ Output dataset ./anat.un.aff.qw_WARP.nii
++ ===== clock time = 2h 5m 6s 275ms
#++ Applying warps to /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig
#Script is running (command trimmed):
  3dNwarpApply -nwarp "./anat.un.aff.qw_WARP.nii anat.un.aff.Xat.1D" -master ./base.nii -source /gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig -prefix ./Sag3DMPRAGEs002a1001_ns.aw.nii 
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is './base.nii'
++ opened source dataset '/gpfs/gsfs8/users/jangrawdc/PRJ16_TaskFcManipulation/RawData/tb7001/tb7001.srtt_v3/Sag3DMPRAGEs002a1001_ns+orig'
++ Processing -nwarp 
++ Warping: .Z
++ Output dataset ./Sag3DMPRAGEs002a1001_ns.aw.nii
++ total Elapsed time = 24.0 sec
#++ Saving history
#Script is running (command trimmed):
  3dNotes -h "auto_warp.py -base MNI152_T1_2009c+tlrc -input \
 Sag3DMPRAGEs002a1001_ns+orig -skull_strip_input no" \
 ./Sag3DMPRAGEs002a1001_ns.aw.nii


3dbucket -prefix Sag3DMPRAGEs002a1001_ns awpy/Sag3DMPRAGEs002a1001_ns.aw.nii
++ 3dbucket: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
mv awpy/anat.un.aff.Xat.1D .
mv awpy/anat.un.aff.qw_WARP.nii .
if ( ! -f Sag3DMPRAGEs002a1001_ns+tlrc.HEAD ) then
foreach run ( 01 02 03 )
3dvolreg -verbose -zpad 1 -base vr_base+orig -1Dfile dfile.r01.1D -prefix rm.epi.volreg.r01 -cubic -1Dmatrix_save mat.r01.vr.aff12.1D pb02.tb7001.r01.tshift+orig
++ 3dvolreg: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./vr_base+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./vr_base+orig.BRIK is 12.699996 degrees from plumb.
++ Reading in base dataset ./vr_base+orig.BRIK
++ Oblique dataset:./pb02.tb7001.r01.tshift+orig.BRIK is 12.699996 degrees from plumb.
++ Reading input dataset ./pb02.tb7001.r01.tshift+orig.BRIK
++ Edging: x=3 y=3 z=2
++ Creating mask for -maxdisp
 + Automask has 31399 voxels
 + 4988 voxels left in -maxdisp mask after erosion
++ Initializing alignment base
++ Starting final pass on 150 sub-bricks: 0..1..2..3..4..5..6..7..8..9..10..11..12..13..14..15..16..17..18..19..20..21..22..23..24..25..26..27..28..29..30..31..32..33..34..35..36..37..38..39..40..41..42..43..44..45..46..47..48..49..50..51..52..53..54..55..56..57..58..59..60..61..62..63..64..65..66..67..68..69..70..71..72..73..74..75..76..77..78..79..80..81..82..83..84..85..86..87..88..89..90..91..92..93..94..95..96..97..98..99..100..101..102..103..104..105..106..107..108..109..110..111..112..113..114..115..116..117..118..119..120..121..122..123..124..125..126..127..128..129..130..131..132..133..134..135..136..137..138..139..140..141..142..143..144..145..146..147..148..149..
++ CPU time for realignment=0 s  [=0 s/sub-brick]
++ Min : roll=-0.188  pitch=-0.043  yaw=-0.440  dS=-0.667  dL=-0.123  dP=-0.179
++ Mean: roll=+0.019  pitch=+0.170  yaw=-0.232  dS=-0.397  dL=+0.090  dP=-0.072
++ Max : roll=+0.128  pitch=+0.347  yaw=+0.165  dS=+0.173  dL=+0.173  dP=+0.107
++ Max displacements (mm) for each sub-brick:
 0.00(0.00) 0.31(0.31) 0.39(0.15) 0.41(0.16) 0.40(0.09) 0.44(0.08) 0.46(0.08) 0.43(0.08) 0.45(0.08) 0.39(0.08) 0.46(0.13) 0.40(0.28) 0.33(0.11) 0.26(0.07) 0.22(0.06) 0.23(0.06) 0.30(0.09) 0.26(0.08) 0.24(0.03) 0.27(0.05) 0.25(0.05) 0.28(0.06) 0.33(0.05) 0.35(0.06) 0.38(0.06) 0.39(0.07) 0.47(0.09) 0.49(0.03) 0.49(0.06) 0.54(0.06) 0.56(0.05) 0.60(0.06) 0.61(0.03) 0.65(0.05) 0.66(0.03) 0.68(0.05) 0.70(0.03) 0.68(0.03) 0.67(0.05) 0.67(0.06) 0.68(0.07) 0.67(0.05) 0.68(0.04) 0.73(0.05) 0.78(0.06) 0.79(0.03) 0.75(0.05) 0.73(0.06) 0.76(0.04) 0.78(0.03) 0.79(0.03) 0.76(0.04) 0.73(0.05) 0.80(0.12) 0.80(0.07) 0.81(0.07) 0.81(0.06) 0.82(0.05) 0.86(0.09) 0.83(0.04) 0.84(0.03) 0.84(0.06) 0.87(0.04) 0.87(0.02) 0.88(0.05) 0.89(0.04) 0.90(0.04) 0.93(0.06) 0.94(0.05) 0.94(0.02) 0.97(0.05) 0.96(0.05) 0.96(0.07) 1.01(0.06) 1.00(0.02) 1.03(0.04) 1.03(0.08) 1.05(0.05) 1.06(0.09) 1.07(0.05) 1.09(0.04) 1.09(0.04) 1.11(0.04) 1.12(0.09) 1.02(0.13) 1.02(0.07) 1.05(0.05) 1.05(0.06) 1.02(0.07) 1.02(0.04) 1.05(0.05) 1.04(0.07) 1.09(0.06) 1.10(0.03) 1.09(0.04) 1.10(0.08) 1.12(0.04) 1.11(0.10) 1.05(0.11) 1.10(0.06) 1.04(0.12) 1.11(0.13) 1.08(0.08) 1.11(0.06) 1.13(0.06) 1.16(0.04) 1.19(0.08) 1.19(0.04) 1.20(0.04) 1.21(0.03) 1.23(0.04) 1.23(0.02) 1.24(0.03) 1.26(0.04) 1.25(0.02) 1.26(0.04) 1.22(0.06) 1.20(0.08) 1.23(0.04) 1.23(0.06) 1.25(0.11) 1.30(0.15) 1.25(0.14) 1.27(0.06) 1.28(0.04) 1.27(0.04) 1.24(0.03) 1.24(0.03) 1.24(0.06) 1.27(0.04) 1.29(0.06) 1.29(0.07) 1.30(0.06) 1.33(0.04) 1.31(0.04) 1.31(0.04) 1.27(0.05) 1.26(0.10) 1.26(0.02) 1.24(0.04) 1.25(0.05) 1.16(0.19) 1.02(0.18) 0.86(0.23) 0.88(0.06) 0.78(0.18) 0.61(0.33) 0.68(0.17) 0.76(0.24) 0.79(0.26)
++ Max displacement in automask = 1.33 (mm) at sub-brick 133
++ Max delta displ  in automask = 0.33 (mm) at sub-brick 146
++ Wrote dataset to disk in ./rm.epi.volreg.r01+orig.BRIK
3dcalc -overwrite -a pb02.tb7001.r01.tshift+orig -expr 1 -prefix rm.epi.all1
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
[7m*+ WARNING:[0m input 'a' is not used in the expression
cat_matvec -ONELINE anat.un.aff.Xat.1D Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -I mat.r01.vr.aff12.1D
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source pb02.tb7001.r01.tshift+orig -nwarp anat.un.aff.qw_WARP.nii mat.r01.warp.aff12.1D -prefix rm.epi.nomask.r01
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb02.tb7001.r01.tshift+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb02.tb7001.r01.tshift+orig.BRIK is 12.699996 degrees from plumb.
++ opened source dataset 'pb02.tb7001.r01.tshift+orig'
++ Processing -nwarp 
++ Warping: ......................................Z
++ Output dataset ./rm.epi.nomask.r01+tlrc.BRIK
++ total Elapsed time = 526.3 sec
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp anat.un.aff.qw_WARP.nii mat.r01.warp.aff12.1D -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r01
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./rm.epi.all1+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./rm.epi.all1+orig.BRIK is 12.699996 degrees from plumb.
++ opened source dataset 'rm.epi.all1+orig'
3dTstat -min -prefix rm.epi.min.r01 rm.epi.1.r01+tlrc
++ 3dTstat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: KR Hammett & RW Cox
end
3dvolreg -verbose -zpad 1 -base vr_base+orig -1Dfile dfile.r02.1D -prefix rm.epi.volreg.r02 -cubic -1Dmatrix_save mat.r02.vr.aff12.1D pb02.tb7001.r02.tshift+orig
++ 3dvolreg: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./vr_base+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./vr_base+orig.BRIK is 12.699996 degrees from plumb.
++ Reading in base dataset ./vr_base+orig.BRIK
++ Oblique dataset:./pb02.tb7001.r02.tshift+orig.BRIK is 12.699996 degrees from plumb.
++ Reading input dataset ./pb02.tb7001.r02.tshift+orig.BRIK
++ Edging: x=3 y=3 z=2
++ Creating mask for -maxdisp
 + Automask has 31331 voxels
 + 4976 voxels left in -maxdisp mask after erosion
++ Initializing alignment base
++ Starting final pass on 150 sub-bricks: 0..1..2..3..4..5..6..7..8..9..10..11..12..13..14..15..16..17..18..19..20..21..22..23..24..25..26..27..28..29..30..31..32..33..34..35..36..37..38..39..40..41..42..43..44..45..46..47..48..49..50..51..52..53..54..55..56..57..58..59..60..61..62..63..64..65..66..67..68..69..70..71..72..73..74..75..76..77..78..79..80..81..82..83..84..85..86..87..88..89..90..91..92..93..94..95..96..97..98..99..100..101..102..103..104..105..106..107..108..109..110..111..112..113..114..115..116..117..118..119..120..121..122..123..124..125..126..127..128..129..130..131..132..133..134..135..136..137..138..139..140..141..142..143..144..145..146..147..148..149..
++ CPU time for realignment=0 s  [=0 s/sub-brick]
++ Min : roll=-0.115  pitch=-0.988  yaw=-0.041  dS=-0.322  dL=-0.071  dP=-0.288
++ Mean: roll=-0.071  pitch=-0.658  yaw=+0.091  dS=-0.091  dL=+0.018  dP=-0.226
++ Max : roll=-0.036  pitch=-0.334  yaw=+0.173  dS=+0.430  dL=+0.121  dP=-0.147
++ Max displacements (mm) for each sub-brick:
 1.70(0.00) 1.64(0.24) 1.82(0.20) 1.89(0.14) 1.96(0.11) 1.93(0.08) 1.86(0.11) 1.95(0.15) 1.95(0.18) 1.70(0.26) 1.60(0.10) 1.52(0.09) 1.53(0.10) 1.55(0.06) 1.56(0.05) 1.58(0.05) 1.58(0.06) 1.56(0.07) 1.53(0.04) 1.51(0.02) 1.47(0.05) 1.47(0.03) 1.46(0.03) 1.46(0.02) 1.47(0.04) 1.41(0.06) 1.46(0.06) 1.45(0.03) 1.45(0.05) 1.44(0.02) 1.43(0.03) 1.47(0.05) 1.49(0.06) 1.45(0.04) 1.46(0.02) 1.52(0.08) 1.52(0.04) 1.52(0.03) 1.49(0.07) 1.46(0.03) 1.46(0.02) 1.38(0.09) 1.42(0.11) 1.36(0.10) 1.37(0.05) 1.34(0.08) 1.32(0.05) 1.31(0.07) 1.32(0.06) 1.31(0.11) 1.32(0.12) 1.30(0.13) 1.29(0.10) 1.33(0.06) 1.36(0.05) 1.35(0.07) 1.37(0.04) 1.38(0.05) 1.37(0.02) 1.32(0.08) 1.30(0.04) 1.32(0.06) 1.35(0.05) 1.35(0.04) 1.31(0.08) 1.28(0.05) 1.30(0.06) 1.35(0.10) 1.35(0.02) 1.33(0.05) 1.33(0.06) 1.33(0.04) 1.35(0.05) 1.33(0.04) 1.31(0.06) 1.32(0.05) 1.32(0.03) 1.31(0.03) 1.32(0.04) 1.29(0.05) 1.30(0.06) 1.31(0.05) 1.32(0.04) 1.32(0.04) 1.23(0.11) 1.27(0.08) 1.28(0.04) 1.30(0.03) 1.25(0.05) 1.21(0.06) 1.25(0.07) 1.25(0.04) 1.25(0.07) 1.31(0.17) 1.22(0.10) 1.18(0.09) 1.29(0.13) 1.24(0.13) 1.17(0.17) 1.18(0.04) 1.10(0.10) 1.10(0.06) 1.13(0.05) 1.15(0.06) 1.18(0.07) 1.13(0.11) 1.10(0.05) 1.15(0.15) 1.14(0.15) 1.08(0.08) 1.08(0.08) 1.06(0.05) 1.06(0.06) 1.08(0.05) 1.09(0.03) 1.10(0.05) 1.02(0.12) 1.04(0.07) 1.05(0.06) 1.03(0.04) 1.03(0.03) 1.05(0.03) 1.04(0.03) 1.02(0.03) 1.04(0.05) 1.04(0.04) 1.03(0.08) 1.01(0.06) 1.00(0.03) 1.03(0.05) 1.01(0.06) 0.95(0.11) 0.91(0.15) 0.94(0.06) 0.94(0.08) 0.93(0.06) 0.91(0.03) 0.94(0.05) 0.94(0.08) 0.96(0.04) 0.94(0.07) 0.99(0.30) 1.01(0.28) 1.10(0.26) 1.08(0.09) 0.98(0.12) 0.94(0.06) 0.98(0.10) 1.08(0.11) 1.10(0.04)
++ Max displacement in automask = 1.96 (mm) at sub-brick 4
++ Max delta displ  in automask = 0.30 (mm) at sub-brick 141
++ Wrote dataset to disk in ./rm.epi.volreg.r02+orig.BRIK
3dcalc -overwrite -a pb02.tb7001.r02.tshift+orig -expr 1 -prefix rm.epi.all1
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
[7m*+ WARNING:[0m input 'a' is not used in the expression
cat_matvec -ONELINE anat.un.aff.Xat.1D Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -I mat.r02.vr.aff12.1D
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source pb02.tb7001.r02.tshift+orig -nwarp anat.un.aff.qw_WARP.nii mat.r02.warp.aff12.1D -prefix rm.epi.nomask.r02
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb02.tb7001.r02.tshift+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb02.tb7001.r02.tshift+orig.BRIK is 12.699996 degrees from plumb.
++ opened source dataset 'pb02.tb7001.r02.tshift+orig'
++ Processing -nwarp 
++ Warping: ......................................Z
++ Output dataset ./rm.epi.nomask.r02+tlrc.BRIK
++ total Elapsed time = 533.0 sec
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp anat.un.aff.qw_WARP.nii mat.r02.warp.aff12.1D -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r02
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./rm.epi.all1+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./rm.epi.all1+orig.BRIK is 12.699996 degrees from plumb.
++ opened source dataset 'rm.epi.all1+orig'
3dTstat -min -prefix rm.epi.min.r02 rm.epi.1.r02+tlrc
++ 3dTstat: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: KR Hammett & RW Cox
end
3dvolreg -verbose -zpad 1 -base vr_base+orig -1Dfile dfile.r03.1D -prefix rm.epi.volreg.r03 -cubic -1Dmatrix_save mat.r03.vr.aff12.1D pb02.tb7001.r03.tshift+orig
++ 3dvolreg: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: RW Cox
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./vr_base+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./vr_base+orig.BRIK is 12.699996 degrees from plumb.
++ Reading in base dataset ./vr_base+orig.BRIK
++ Oblique dataset:./pb02.tb7001.r03.tshift+orig.BRIK is 12.699996 degrees from plumb.
++ Reading input dataset ./pb02.tb7001.r03.tshift+orig.BRIK
++ Edging: x=3 y=3 z=2
++ Creating mask for -maxdisp
 + Automask has 31294 voxels
 + 4940 voxels left in -maxdisp mask after erosion
++ Initializing alignment base
++ Starting final pass on 150 sub-bricks: 0..1..2..3..4..5..6..7..8..9..10..11..12..13..14..15..16..17..18..19..20..21..22..23..24..25..26..27..28..29..30..31..32..33..34..35..36..37..38..39..40..41..42..43..44..45..46..47..48..49..50..51..52..53..54..55..56..57..58..59..60..61..62..63..64..65..66..67..68..69..70..71..72..73..74..75..76..77..78..79..80..81..82..83..84..85..86..87..88..89..90..91..92..93..94..95..96..97..98..99..100..101..102..103..104..105..106..107..108..109..110..111..112..113..114..115..116..117..118..119..120..121..122..123..124..125..126..127..128..129..130..131..132..133..134..135..136..137..138..139..140..141..142..143..144..145..146..147..148..149..
++ CPU time for realignment=0 s  [=0 s/sub-brick]
++ Min : roll=-0.542  pitch=-1.122  yaw=+0.012  dS=-0.787  dL=-0.347  dP=-0.420
++ Mean: roll=-0.225  pitch=-0.680  yaw=+0.158  dS=-0.435  dL=-0.134  dP=-0.163
++ Max : roll=-0.009  pitch=+0.090  yaw=+0.250  dS=-0.030  dL=+0.005  dP=-0.070
++ Max displacements (mm) for each sub-brick:
 1.80(0.00) 1.59(0.24) 1.63(0.07) 1.65(0.08) 1.66(0.05) 1.67(0.10) 1.79(0.14) 1.53(0.56) 1.65(0.30) 1.62(0.13) 1.60(0.12) 1.58(0.13) 1.62(0.10) 1.66(0.07) 1.68(0.05) 1.67(0.04) 1.67(0.04) 1.70(0.03) 1.72(0.04) 1.71(0.05) 1.75(0.05) 1.74(0.02) 1.77(0.04) 1.75(0.06) 1.73(0.04) 1.76(0.05) 1.77(0.01) 1.79(0.03) 1.79(0.02) 1.80(0.03) 1.82(0.03) 1.82(0.09) 1.82(0.04) 1.82(0.02) 1.81(0.04) 1.81(0.04) 1.81(0.03) 1.83(0.05) 1.84(0.04) 1.82(0.02) 1.82(0.02) 1.79(0.08) 1.79(0.07) 1.78(0.04) 1.78(0.06) 1.80(0.05) 1.75(0.08) 1.76(0.03) 1.77(0.04) 1.76(0.04) 1.78(0.04) 1.79(0.04) 1.79(0.04) 1.77(0.04) 1.76(0.05) 1.76(0.05) 1.75(0.04) 1.76(0.03) 1.72(0.07) 1.77(0.07) 1.74(0.11) 1.67(0.10) 1.66(0.04) 1.70(0.05) 1.68(0.06) 1.67(0.04) 1.65(0.05) 1.67(0.04) 1.70(0.06) 1.71(0.07) 1.68(0.08) 1.68(0.03) 1.68(0.04) 1.67(0.05) 1.67(0.03) 1.66(0.08) 1.65(0.05) 1.67(0.07) 1.69(0.04) 1.70(0.03) 1.67(0.04) 1.66(0.04) 1.68(0.04) 1.66(0.02) 1.64(0.05) 1.69(0.06) 1.65(0.05) 1.65(0.02) 1.62(0.09) 1.62(0.02) 1.64(0.04) 1.65(0.05) 1.67(0.03) 1.69(0.02) 1.62(0.14) 1.65(0.17) 1.62(0.13) 1.65(0.04) 1.63(0.04) 1.66(0.04) 1.69(0.05) 1.63(0.09) 1.66(0.03) 1.63(0.12) 1.58(0.07) 1.59(0.08) 1.63(0.09) 1.63(0.03) 1.65(0.02) 1.64(0.04) 1.61(0.03) 1.62(0.08) 1.62(0.05) 1.59(0.04) 1.60(0.08) 1.61(0.07) 1.55(0.12) 1.57(0.06) 1.57(0.03) 1.58(0.02) 1.58(0.04) 1.56(0.03) 1.59(0.04) 1.60(0.08) 1.58(0.07) 1.58(0.03) 1.56(0.05) 1.58(0.03) 1.43(0.26) 1.46(0.58) 1.51(0.07) 1.56(0.06) 1.53(0.06) 1.55(0.05) 1.59(0.06) 1.61(0.04) 1.58(0.08) 1.55(0.08) 1.58(0.04) 1.61(0.04) 1.62(0.03) 1.58(0.11) 1.43(0.27) 1.14(0.43) 1.14(0.09) 1.17(0.07) 1.19(0.16) 1.16(0.29) 1.03(0.30) 0.95(0.25)
++ Max displacement in automask = 1.84 (mm) at sub-brick 38
++ Max delta displ  in automask = 0.58 (mm) at sub-brick 129
++ Wrote dataset to disk in ./rm.epi.volreg.r03+orig.BRIK
3dcalc -overwrite -a pb02.tb7001.r03.tshift+orig -expr 1 -prefix rm.epi.all1
++ 3dcalc: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: A cast of thousands
[7m*+ WARNING:[0m input 'a' is not used in the expression
cat_matvec -ONELINE anat.un.aff.Xat.1D Sag3DMPRAGEs002a1001_al_junk_mat.aff12.1D -I mat.r03.vr.aff12.1D
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source pb02.tb7001.r03.tshift+orig -nwarp anat.un.aff.qw_WARP.nii mat.r03.warp.aff12.1D -prefix rm.epi.nomask.r03
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./pb02.tb7001.r03.tshift+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./pb02.tb7001.r03.tshift+orig.BRIK is 12.699996 degrees from plumb.
++ opened source dataset 'pb02.tb7001.r03.tshift+orig'
++ Processing -nwarp 
++ Warping: ......................................Z
*** Datablock write error: Write error in brick file: Is disk full, or write_protected?
++ Output dataset ./rm.epi.nomask.r03+tlrc.BRIK
++ total Elapsed time = 570.2 sec
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp anat.un.aff.qw_WARP.nii mat.r03.warp.aff12.1D -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r03
++ 3dNwarpApply: AFNI version=AFNI_17.3.09 (Dec 22 2017) [64-bit]
++ Authored by: Zhark the Warped
++ -master dataset is 'Sag3DMPRAGEs002a1001_ns+tlrc'
++ output grid size = 3 mm
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as ./rm.epi.all1+orig.BRIK,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:./rm.epi.all1+orig.BRIK is 12.699996 degrees from plumb.
++ opened source dataset 'rm.epi.all1+orig'
pigz: write error code 122
pigz: abort: write error on <stdout>

Fatal Signal 13 (SIGPIPE) received
     THD_nwarp_regrid
    IW3D_set_geometry_nwarp_catlist
   IW3D_read_nwarp_catlist
  3dNwarpApply
 Bottom of Debug Stack
** Command line was:
3dNwarpApply -master Sag3DMPRAGEs002a1001_ns+tlrc -dxyz 3 -source rm.epi.all1+orig -nwarp 'anat.un.aff.qw_WARP.nii mat.r03.warp.aff12.1D' -interp cubic -ainterp NN -quiet -prefix rm.epi.1.r03
** AFNI version = AFNI_17.3.09  Compile date = Dec 22 2017
** [[Precompiled binary linux_openmp_64: Dec 22 2017]]
** Program Death **
** If you report this crash to the AFNI message board,
** please copy the error messages EXACTLY, and give
** the command line you used to run the program, and
** any other information needed to repeat the problem.
** You may later be asked to upload data to help debug.
** Crash log is appended to file /home/jangrawdc/.afni.crashlog
